### ISSUE TITLE
Zaměstnat člověka do Pyvce

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#13]
Najmout na rok dedikovaného člověka na věci posunující Python v ČR vpřed. Uvolní to ruce nám a umožní větší záběr a větší důslednost, než když je to čistě dobrovolný. Rok by byl zkušební, člověk by musel ukázat, že jeho pozice má smysl a že se umí otáčet. Když to půjde, budeme se snažit vymyslet jeho financování dál (a on se to bude snažit vymyslet s náma :-) ).

Detaily v [dokumentu](https://docs.google.com/document/d/1Kb-JYvqPTftEkZupnVJNgjBP5TlQhrJKc_MPIo7Dudk/edit?usp=sharing).

**Comment by lspdv** [comment]
Bude se toto nekam hybat? Konkretne ted by se ten clovek vazne hodil.

Lobbuju:
- za cloveka, ktery navic bude umet HTML/CSS
- za cloveka, ktery by stihl resit veci co nejdriv, protoze jich je ted dost a ne aby se najmul az kdyz se to vsechno udela a pak se bude do dalsiho sprintu nebo barcampu lenosit. Po tehle akcich evidentne prichazi vlna novych napadu

**Comment by honzajavorek** [comment]
Myslím, že se to už trochu hýbe.

**Comment by honzajavorek** [comment]
Toto jsme vyzkoušeli a nakonec to nedopadlo. Momentálně nevím o tom, že by byla tak velká poptávka, že bychom tento nápad opět otevírali. Třeba se k němu někdy vrátíme.

**Comment by lspdv** [comment]
👍🏻

so 26. 8. 2017 v 13:40 odesílatel Honza Javorek <notifications@github.com>
napsal:
