### ISSUE TITLE
Nástroj na automatizované nahrávání videí na YouTube

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#14]
@honzajavorek: @encukou by mohl sepsat požadavky. V podstatě jde o jednoduchý nástroj, kterému dáme video s přednáškou a on ho nahraje na YouTube bez nějakého klikání. Nemusí se to programovat, pokud někdo najde, že už je to hotové.

Souvisí s https://github.com/pyvec/zapojse/issues/4

---

@encukou 

Právě zpracovávám pražské Pyvo, tak to sem zapíšu :)
-    Nahrát video na daný Youtube účet, s daným názvem, popiskem, tagem
-    Přidat do daných playlistů (+vytvořit playlist pokud neexistuje)
-    Nejlépe počkat, až YT video zpracuje
-    Vrátit URL videa (aby se to dalo strčit třeba na Lanyrd)

---

@honzajavorek: @encukou myslis, ze by se dalo i nejak zautomatizovat doplnovani tech jmen prednasejicich?

---

@encukou: Jména přednášejících potřebuje už skript, který to video vytváří, a ze kterého chci ten uploader volat, takže mu je můžu prostě předat :)
Jinak ano, jména bude časem potřeba je brát z Lanyrdu, nebo z python.cz a pak doplňovat i na Lanyrd, nebo jak to uděláme, ale to je spíš součást automatizace infa o srazech.

---

@pocin:
YT ma svoje API a zde je primo predpripraveny kod k uploadu videa. Nestudoval jsem to nejak detailne, ale melo by to jit:

https://developers.google.com/youtube/v3/code_samples/python#upload_a_video

---

@honzajavorek:
Našel jsem něco hotového na GitHubu:

https://github.com/tokland/youtube-upload

Mohli bychom to forknout / přizpůsobit / využít / dodat pull requesty. cc @encukou 

---

@pocin: Je to ještě aktuální, případně v jakém je to stavu?
Rád bych se toho ujal.

---

@encukou:

Aktuální to je. Mám video a takovýhle YAML soubor (s pomocí jsem do toho videa dal titulky):

```
speaker: Jiří Bartoň & Jakub Vysoký
title: "Auth*"
event: Pražské Pyvo
date: 2016-02-20
url: http://lanyrd.com/2016/praha-pyvo-january/
speaker_only: true
speaker_vid: '*.MTS'
praha: true
```

Bylo by fajn udělat commandline aplikaci která tyhle dva soubory vezme, vytvoří titulek a popisek jako na https://www.youtube.com/watch?v=MSpg0j712E4 , a nahraje to na Youtube. Případně ještě přidá do playlistu.

---

@pocin: Ups, nechodi mi notifikace. @petrviktorin Okej, jak si najdu chvilku, tak se do toho dam :)
Jeste technicky dotaz: 1. kazde video ma svoji slozku a ta obsahuje YAML + dane video, ktere se jmenuje neconeco.MTS?
2. te casti s titulkama jsem vubec neporozumel :(

---

@pocin:

Prvni verze quick 'n dirty verze.
https://github.com/pocin/pyvo_yt_uploader (ma python.cz nejakou repo? klidne to nahraju tam)
Jako subprocess pousti youtube-upload, jak navrhnul Honza Javorek.

Zatim resi video title a description.
Neni problem dodelat pridani do playlistu, ale musim vedet z ceho odvodit jeho nazev.

Dale neni problem cokoliv dodelat, nebo predelat. Pokud by README byl nesrozumitelny, tak na tom zapracuju. Jakakoliv kritika vitana :)

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/q7dT6LwM/24-nastroj-na-automatizovane-nahravani-videi-na-youtube).

**Comment by encukou** [comment]
Tak, na tohle jsem úplně zapoměl. Velice se omlouvám @pocin a @oskar456 za duplikátní práci :(

https://github.com/pocin/pyvo_yt_uploader
https://github.com/oskar456/talk-video-uploader

@oskar456 má workflow i s tvorbou videí a daty pro pyvo.cz, takže s dovolením bych používal spíš to.

**Comment by pocin** [comment]
haha  :-D @oskar456 to má stejně pěknější
