### ISSUE TITLE
meetup.com

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#15]
Vytvořit a spravovat meetup.com pro srazy, aby nás našli i lidi z jiných zemí, když tudy projíždějí. Pražské Pyvo už něco má, ale možná to dokonce platí @whiskybar sám, nevíme.

Asi by to měl platit Pyvec a měli by si to zakládat všechny Pyva. Taky PyLadies chtěly meetup.com nebo co že to :) cc @lspdv

**Comment by lspdv** [comment]
PyLadies ho moc nechteji. Nicmene existuje jiz meetup PyLadiesCZ, ktery je zalozeny na Brno, organizator je Lynn a chce ho na nas prehodit. Nicmene ja nejsem zastance rozsirovani soc siti o dalsi a tudiz nevim moc dobre co s tim. @whiskybar dej vedet jak funguje to Pyvo, zdali to platis a neresis nebo platis a nechavas proplatit, @encukou zminoval neco ve smyslu, ze udelat profil primo na Pyvec nelze a ze to stejne musi jit pres FO.

**Comment by lspdv** [comment]
A muj uprimny nazor: vsechny tyto Google+, meetup, srazy.info apod jsou pritez navic na kterou nikdo z nas nema kapacitu, dokud **Pyvec nebude mit osobu administrativniho typu, jenz se bude moc alespon 3 hodky tydne vsem temhle sitim venovat, bude mit pristupy, bude mit prehled**

**Comment by honzajavorek** [comment]
Co znamena FO? Jinak ano, ja ted nemam ani nutnost treba do meetup.com v Brne jit, protoze tam mam lidi habadej a sil nekde neco takhle sefovat moc neni.

**Comment by aleszoulek** [comment]
Ja muzu jen rict, ze meetup pro prg-pyvo funguje a oslovuje nove lidi,
kteri o srazech jinak nevedeli. Rozhodne bych rekl, ze vic jak lanyrd.

Ale hlavne, my nechcem ani tak admina s 3h tydne, ale poradny vstupni data
(jeden jasnej zdroj, kde je vsechno cas, misto, popis, serie)  a tool,
kterej to nasype. Zatim nemame poradne ani jedno. Asi bychom meli zacit s
tema datama.

Ja si tak predstavuju naivne google cal, kam budou mit admini eventu
pristup, pekne tam tu udalost vyplnej. Ale muze to bejt i nejakej
spreadsheet.. To je asi implementacni detail.

A.

**Comment by encukou** [comment]
Data jsou tady: https://github.com/pyvec/pyvo-data

**Comment by whiskybar** [comment]
Presne tak. Ja to zalozil, protoze na meetup.com lidi lezou uplne nejvice, kdyz chtej na sraz a nevedi nic dalsiho. To je proste fakt, overeno v terenu.

Sice nemam cas/energii editovat udalosti na meetup.com, ale staci, ze je tam pravidlo "kazda 3. streda v mesici" a ono to pocita samo a spousta lidi za ten 1 rok existence diky tomu prisla na sraz. Cili to funguje dobre uz tak, jak to je -- tolik @lspdv, ze mit meetup.com je lepsi mit nez nemit. (samozrejme mit lidi na extra update by bylo lepsi).

Samozrejme bych chtel, kdyby to platil Pyvec, ale proste je s tim takovyho s****i, ze mi prislo nejlevnejsi to zaplatit, nez nekam psat email, zadat, pak si poslechnout, ze by to chteli i dalsi srazy atp. Rozhodne se tomu nebranim.

Kdyz to shrnu, pro zacatek staci
1. presvedcit Pyvec, ze to ma smysl a vydyndat na to penize
2. zalozit opakujici srazy s pravidly
3. profit

Pravidelne updaty bych resil pozdeji.

**Comment by lspdv** [comment]
Dik za info @whiskeybar :-)

**Comment by aleszoulek** [comment]
@encukou Super. Hele melo by smysl mit i data pro dalsi eventy? Jakoze gymgeek? mseno sprint? pycon?

@whiskybar Kolik ten meetup.com stoji $$$ ?

**Comment by honzajavorek** [comment]
@aleszoulek 💸 http://lmgtfy.com/?q=meetup.com+pricing 💸

**Comment by encukou** [comment]
> @encukou Super. Hele melo by smysl mit i data pro dalsi eventy? Jakoze gymgeek? mseno sprint? pycon?

Mělo. Než se taková data mergnou tak bude chtít změnit i pyvo.cz, jinak se tam můžou klidně dávat.

**Comment by honzajavorek** [comment]
Vypadá to, že by @janbleha chtěl založit meetup.com i pro Brno (kde se tomu nebráníme, jen jsme neměli energii to zakládat a spravovat).

@encukou 

> I wouldn't mind if someone either copied pyvo meetups there, or wrote an importer (from some standard format – iCal, RSS, ...,  or even custom JSON). If Jan Bleha runs it and it's Jan's job to keep it up to date, no problem :)
> I'm keeping pyvo.cz up to date, copying from whatever main source of truth the organizers use (though I'm happy that many update pyvo.cz directly now). If Jan copies the stuff to meetup.com, godspeed to him :)

Já bych si nějak chtěl ujasnit pár věcí:

- Jsme schopni se mezi městy shodnout na tom, co je primární zdroj pravdy o Pyvech?
- Jsme schopni začít používat jen dvě věci, a to pyvo.cz a meetup.com?
- Jakým způsobem chceme platit meetup.com a starat se o to? (Pyvec? každá aktivita samostatně ze svého?)

Já jsem ochotný v Brně úplně vyměnit meetup.com za Facebook, kde teď jsme primárně. I když se ale Honza Bleha nabídne to platit a spravovat, chci ale potom např. přístup (i když to nebude moje primární práce to tam dávat), abych mohl jako org komunikovat s lidma, nahrávat případně fotky, opravit chybu v popisu, apod. Nebo jak to říct - nechci, aby meetup.com pro brněnské Pyvo "patřil" Kiwi.com a raději bych třeba, kdyby ty peníze šly přes Pyvec (tzn. Kiwi.com přispívá na Pyvec, Pyvec přispívá na Pyvo).

Další věc - bylo by dobré vědět, kam dát informace jako první a co je sekundární zdroj. Nebo můžeme říct, že je to jedno, ale že by měla být snaha mít to na obou stejně. Pak můžeme napsat #27, který bude mít jen dvě funkce - 1. bude umět archivovat informace z meetup.com do pyvo.cz a 2. bude umět založit meetup.com z informací na pyvo.cz. Když si to ujasníme, rád ten nástroj začnu na sprintech vyrábět.

@frenzymadness co Ostrava a meetup.com?

**Comment by frenzymadness** [comment]
@honzajavorek My máme zatím srazy.info, facebook.com a pyvo.cz. Facebook nám dělají PyLadies a o zbytek se starám já. Nejsem proti přechodu ze srazy.info na meetup.com, protože stejně nevíme, jak dlouho srazy ještě poběží, ale prozatím jsem v tom neviděl tu přidanou hodnotu, která by vývážila investované peníze. Je tam vůbec nějaká?

**Comment by kvbik** [comment]
@frenzymadness pridana hodnota: meetup je zkratka celosvetovy srazy.info s ohromnou uzivatelskou zakladnou. takze prvni, co jsem udelal ted po prijezdu do madridu, ze jsem hledal na meetup.com co je tady za komunity. a pro prahu to funguje uplne stejne. novi lide chodili samozrejme i bez meetup.com, ale myslim, ze to je o rad jinde.

@honzajavorek souhlas s tebou! mne by se rozhodne libilo, kdyby to slo kiwi->pyvec, protoze jsou to komunitni veci, na druhou stranu super, ze @janbleha nabizi pomoc, protoze to administrovani nejaka prace je!

myslim, ze takovy zakopany vecny tema tady je, jestli meetup.com nabizi nejake ucty pro organizace. abychom to mohli nejak administrovat. nebo proste tohle nejak rozseknout. ja napriklad muzu odpovidat na maily ohledne prazskeho pyva, pritom ten meetup je zalozeny by @whiskybar  a to je super, lidi se ozyvaji.

**Comment by honzajavorek** [comment]
Praha meetup.com má, PyLadies to mají taky a sporadicky to používají-nepoužívají mi přijde, Ostrava má svoje srazy.info, Brno má pořád svůj Facebook (meetup.com jsme pak už nějak neřešili), do toho dál existuje pyvo.cz, ...

Mě by se líbilo, kdyby se informace o Pyvu vkládaly do pyvo-data a centrální místo bylo pyvo.cz. Na všechny další sítě by pak stačilo dát prostě do popisu odkaz na event na pyvo.cz a je to. Žádnou duplikaci dat bych nedělal, žádné programy, které budou ty informace posílat přes API na FB nebo meetup.com bych nepsal.

Co se týče akcí, které nejsou Pyvo, vymysleli jsme včera na sprintu, že cestou ke štěstí možná není unifikace a centralizace, ale nějaké "federační" řešení. Tedy že každý si pojede na čem chce, ale bude centrální místo, kde bude seznam událostí a zapojit se do něj bude moct kdokoliv z jakéhokoliv systému, přes API zvané `.ical` :) Ať už jsou to Pyva, nebo cokoliv jiného... https://github.com/pyvec/python.cz/issues/220

-------

Pokud bychom se tedy shodli na tom, že

- primární zdroj dat pro Pyvo srazy bude `pyvo-data` a pokud chce někdo něco navíc, ať si to má
- pokud chce nějaká aktivita meetup.com, ať jde za Pyvcem a poprosí ho o založení a proplacení, posuzovat se bude na individuální bázi
- ostatní eventy ať si dělá kdo chce jak chce, pokud dodá `.ical` nebo Google Kalendář

...tak to tu můžeme zavřít. Názory?

@encukou @messa @kvbik @aleszoulek @whiskybar @frenzymadness

**Comment by lspdv** [comment]
Tak mi pak prosim dejte vedet, jestli ten meetup.com pro PyLadies mam
prestat platit. Nerada bych ho platila jeste vic zbytecne nez ted. PyLadies
ho aktualne pouzivaji jen na Advanced PyLadies srazy a to proto, ze si to
vyzadala Lynn Root aby se nerusil. Osobne v nem prinos nevidim, ale tusim,
ze @encukou by nebyl uplne rad kdybych ho jen tak smazala. Proto ho drzim.

**Comment by honzajavorek** [comment]
To se musíme zeptat PyLadies. @zoellenka říkala, že na PyWorking to nakonec nepoužívají a bude #60. @ivafingerova meetup.com na Advanced PyLadies chce/nechce? Co zbytek PyLadies - @zuzejk, @paffilda?

**Comment by zoellenka** [comment]
Pro Pyworkingy je to málo závazné, a potřebujeme s účastníky více komunikovat, ohledně prerekvizit atd. Mailové formuláře na to vyhovují více.

**Comment by IvaFingerova** [comment]
PyLadies Advanced na tom zatím frčí a rozšiřuje se nám tam základna přívrženců, ale spousta z nich jsou nějaké zbloudilé duše + se tyto zbloudilé duše čas od času dorazí, nemají připravené projekty a přijdou s nějakým nejistým očekáváním :) 
Myslím, že FB eventy by nám posloužily stejným způsobem.

**Comment by lspdv** [comment]
Take si to myslim Ivouni :-))

**Comment by frenzymadness** [comment]
Pořád se o tom mluví, tak já bych to rád alespoň vyzkoušel a následujících pár Pyv dávál kromě pyvo.cz, srazy,info a facebooku i na meetup.com a časem se třeba na facebook a srazy.info vykašleme úplně.

Je na meetup.com něco jako naše organizace, kam bych se mohl zapojit a dávat tam eventy pro Ostravské Pyvo?

**Comment by honzajavorek** [comment]
Není, meetup.com neumí složitější organizační strukturu. V zásadě musí mít
každý sraz svůj účet.

**Comment by honzajavorek** [comment]
Máme v komunitě hodně meetup.com účtů a asi bych už neviděl smysl v tom to nějak centralizovat. Pokud někdo potřebuje meetup.com používat, ale nechce ho platit, nechť se ozve Pyvci a vymyslíme, jak za to platit. Zavřel bych to tady. Názory?
