### ISSUE TITLE
Putovní Pyvo

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#16]
oběžní Pyvo, udelat tour po republice po mensich mestech... bydlet normalne klidne v nejakych penzionech

Domluvit se s mistnimi srazy, ze to dane jejich vydani bude s privlastkem Pyvo a bude o Pythonu, tim bude zajisteno nejake zazemi a publikum

V nekterych mestech kde nic neni by se dalo mozna zarezervovat neco sami, ale spis bych se tomu vyhnul

Klidne tydenni tour nebo tak neco, sranda musi bejt

**Comment by frenzymadness** [comment]
Skvělý nápad. Jdeme do toho!

**Comment by honzajavorek** [comment]
@frenzymadness Já to tady jen tak vyhodil z hlavy jako bláznivý nápad. Dáš tomu nějakou reálnou formu a zorganizuješ to? 😜

**Comment by frenzymadness** [comment]
@honzajavorek Popřemýšlím nad tím. Naplánovat to jako tour bude asi náročné, ale proč to nezkusit :+1: 

Začal bych něčím jednoduchým, co není daleko a pak se uvidí. Taky by bylo fajn, kdybych nedělal tu invazi do nějakého lokálního srazu sám, aby to nevypadalo blbě.

Na první test mě napadli Tkalci, kteří mimo jiné jednou navštívili Pyvo v Ostravě. http://srazy.info/tkalci-na-webu/6483

**Comment by aleszoulek** [comment]
Krom toho v CB jsou "Crtvrtkony"

https://www.facebook.com/groups/347231742084555/

**Comment by aleszoulek** [comment]
Mozna uz jenom dat dohromady ceske (hlavne mimoprazske) meetupy, srazy a IT
komunity, by mohlo stat za to.

**Comment by honzajavorek** [comment]
Nejdriv si pojdme dat dohromady seznam nejakych adeptu, kam zajet. Vynechme uplne mesta, kde existuji Pyva - tam se nejak navstevujem a neni smyslem putovniho Pyva to resit. Putovni Pyvo je o mestech, kde Python neni. Takze me uplne z hlavy napadaji:
- Tkalci, Valasske Mezirici, cc @msgre
- Čtvrtkon, Ceske Budejovice, cc @Twista

**Comment by honzajavorek** [comment]
Jeee vidim ze ste to tu uz psali, ja to cetl nejak napreskacku v mailu.

**Comment by kvbik** [comment]
plus za budejovice nam psal @frantisekrehor

v plzni bylo kdysi jedno pyvo, ale tamni organizatori chodi obcas na prazske a na plzen nemaji cas - na druhou stranu tam mame @whiskybar

**Comment by frantisekrehor** [comment]
Kluci přijeďte! Máme v ČB Masné krámy 🍻 😄

**Comment by VerosK** [comment]
Vídeň má Django meetupy!

**Comment by starenka** [comment]
jj, Viden je takovy okresni mesto :D

**Comment by frenzymadness** [comment]
@honzajavorek Nechtěl bys tento nápad nějak prohnat ve volné chvilce přes Twitter? Třeba se nám přihlásí nějaký další sraz.

Za mě bych to asi viděl až na příští rok na jaro. Do té doby mají všichni beztak starostí dost.

**Comment by honzajavorek** [comment]
@frenzymadness Nic jsem Twitterem neprohnal, ale máš tam přístup, tak můžeš prohnat i sám :)

**Comment by frenzymadness** [comment]
Mám to v Todo stále, ale nevím, jakým směrem to uchopit. Tour na týden je nereálná, protože ty srazy jsou pokaždé jinak a často ani ne pravidelně.

Taky se mi moc nezdá, že by to mělo být fomou "okupace" srazu a jeho předělání na Pyvo verzi resp. zdá se mi, že by se těžko hledal sraz, kde by se to mohlo setkat s pozitivním přijetím. Když si představím sebe, že by mi někdo ze srazu, který se točí třeba kolem UX udělal Python verzi, to by se mi asi moc nelíbilo.

Co to udělat tak, že si vytipujeme srazy a jejich termíny, kdy je na nich nějaké téma, které je s Pythonem slučitelné,, přijít tam s přednáškou zapadající do jejich konceptu a na konci dát lightning talk o naší komunitě a Pyvech? Já jsem to nějak podobně udělal na PySilesia, kde to teda nebylo složité, protože je to Python sraz.

**Comment by kvbik** [comment]
presne jak pises @frenzymadness - proste jenom udelat vylety, kdyz se bude hodit tema. napr s temi ceskymi budejovicemi uz o tom mluvime rok :))) jsem 💯 za.

**Comment by honzajavorek** [comment]
Já jsem taky pro. Ale původní nápad byl teda udělat to i v místech, kde
žádný Pyvo teď není. Proste one-off event, kam přijdou místní. A třeba se
pak dohodnou, ze v tom budou prokracovat sami, jestli mi rozumíš. Zajímavý
by mi přišly města jako Plzeň, Liberec, Zlín, Olomouc, Pardubice/HK, ...
takový kde nic není. Samozřejmě lepší když bychom věděli, že tam vůbec
někdo přijde - třeba v HK je Rosti, v Plzni taky známe lidi, v Olomouci
jednoho dva, ... ale třeba ve Zlíně nevím o nikom.

**Comment by frenzymadness** [comment]
Jóó Olomouc, tam by to chtělo vykopnout a přidat nám špendlík na Pyvní mapu a tohle je k tomu ideální příležitost.

Co na to @fivaldi a @mcurlej

**Comment by starenka** [comment]
FYI: Jesli si pamatuju dobre z lonskyho (brnenskyho) pyconu, tak sem tak
kecal s nejakyma klukama z budejc (tak cca 3-4) a voni prave rikali, ze je
to na hovno, ze tam nemaj py srac, ze musi chodit na ty nette srazy nebo
co... mena samozrejme nevim...

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by fivaldi** [comment]
@frenzymadness Tak my už tu samozřejmě kujeme pikle. 😉 Pošli nám pls minimal requirements a my něco vymyslíme.

**Comment by Twista** [comment]
jojo, co se tyce CB tak tu python dela 5 lidi (o kterych vim i skrze ostatni meetupy jako ctvrtkon/dev-pivo co poradame) - z toho 4 jsme z jedny firmy a chodime na pivko spolu celkem pravidelne :D

nette-pivo jsme pretransformovali na dev-pivo a je to stejne setkani par tech samych lidi, kde sem tam i python zazni :)

Kdyby byl ale zajem udelat nejakou akci v budejkach a nasli by se lidi co by si vzali treba talk, vse ostatni zaridim

**Comment by frenzymadness** [comment]
@fivaldi Tady je to aktuálně o něčem jiném, ale tvé nadšení se mi líbí a tak jsem udělal samostatné issue k Pyvu v Olomouci.

Kdo se chce přidat, tak sem: https://github.com/pyvec/zapojse/issues/61

**Comment by frenzymadness** [comment]
@Twista, a máte nějakou akci aktuálně v plánu, na kterou bychom se mohli přidat?

**Comment by honzajavorek** [comment]
Chtěl by toto ještě někdo dělat? Zatím to vypadá, že založit v malém městě Pyvo je jednodušší, než se zdálo. Možná toto issue už nemá smysl?

**Comment by encukou** [comment]
Já myslím že nemá.
Říct kolegům z Horní Dolní ať si přijdou k sousedům nabrat speakery mi přijde schůdnější než organizovat turné :)

**Comment by honzajavorek** [comment]
Jestli souhlasí i @frenzymadness, který tady psal, že by do toho jít chtěl, tak bych to tu zavřel.

**Comment by frenzymadness** [comment]
Souhlasím. Není na to čas a Pyva už jsou beztak na každém rohu.
