### ISSUE TITLE
Založit hands-on sraz v Brně

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#17]
uz pred nejakou dobou jsme uvazovali, ze bychom udelali nejaky druhy sraz, ktery:
- by byl kazdy tyden
- by byl neorganizovany
- lidi, kteri by potrebovali neco resit, by prisli na nejake misto, sedli by si, bylo by tam wifi, zasuvky a sem tam nejaky kouc a mohli by si to tam v klidu resit a pripadne se nekoho zeptat kdyby si nevedeli rady, pripadne si pomoct navzajem
- v podstate takova free coding session kde se potuluji koucove (kteri nemusi byt oficialni “koucove”, proste kdokoliv kdo danemu cloveku umi pomoct mu pomuze, muze si tam klidne i sam zrovna neco kodit)

v podstate to navazuje na to jak funguji v Brne ctvrtecni PyLadies srazy, akorat by to bylo pro kohokoliv a na vetsim prostoru a s vetsi propagaci

nemame pro to jeste nazev, ale to je fuk

rodi se to pomalu i v Praze, mozna se k tomu dostanou i prazske PyLadies

v podstate jedine co chybi aby se to stalo je
- clovek co by to organizoval
- misto

no a na jednom z Pyv za mnou a @encukou prisli lidi z SU na FITu ze maji prostor pod Pivovarem a jestli do nej neprijdeme udelat prednasku

jak me to popisovali, tak me prislo, ze ten prostor by se super hodil na ty hands-on sraziky

jenze misto abychom si na ne vzali kontakty, tak si vzali jen oni na nas a uz se neozvali

**Comment by lspdv** [comment]
"rodi se to pomalu i v Praze, mozna se k tomu dostanou i prazske PyLadies" - napsal jsi to pred 17 dny, mam opravneny duvod si myslet, ze netusis co jsou Advanced PyLadies a jak jsou skvele! @honzajavorek

**Comment by honzajavorek** [comment]
@lspdv ten text jsem napsal nekdy v cervenci, mozna dokonce v cervnu, nekam na Slack, a pak to sem behem #pythonsprint nakopiroval :) Pokud to tak misty uz funguje, tak samozrejme super!

**Comment by lspdv** [comment]
@honzajavorek splnuje tve pozadavky soucasne NePyvo v Brne? Zavirame?

**Comment by encukou** [comment]
Jo, NePyvo je dostatečně blízko :) Zavírám.

**Comment by honzajavorek** [comment]
Ano, NePyvo (Brno), PyWorking (Praha), vše to splňuje 👍

**Comment by lspdv** [comment]
Luvly

2017-02-02 14:08 GMT+01:00 Honza Javorek <notifications@github.com>:
