### ISSUE TITLE
Zapojit VimVic.cz jako sponzory Django Girls / PyLadies

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#19]
Nabídli se mi sami, že až bude něco potřeba, máme dát vědět. Vidí synergii v tom, že dělají video online kurzy a že DG a PL jsou taky kurzy.

cc @lspdv

**Comment by lspdv** [comment]
Ja uz tohle komentovala, ale neni tu ma odpoved.

Takze, rada je budu kontaktovat. Zkusim se do toho pustit pristi tyden.

**Comment by honzajavorek** [comment]
Tak si u me prosim pak rekni o kontakt na konkretniho cloveka, ktery me s
tim oslovil, dam ti na nej mail atd.

**Comment by honzajavorek** [comment]
@lspdv na základě https://github.com/pyvec/zapojse/issues/33#issuecomment-276775174 bych to tady teda zavřel.
