### ISSUE TITLE
Aktuální český Python tutoriál

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#2]
Existují
- http://programujte.com/clanky/54-serial-python
- http://www.root.cz/serialy/letajici-cirkus/

Má cenu je zkoušet nějak aktualizovat a poskytnout tak lidem další zdroje v češtině? Chopil by se toho někdo?

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/bkMKLfot/44-aktualni-cesky-python-tutorial).

**Comment by honzajavorek** [comment]
@encukou Tenhle meta issue vlastně teď už můžem asi zavřít, ne? Když už máme nástřel http://naucse.python.cz

**Comment by encukou** [comment]
Aha, tohle byla kartička z dob před PyLadies materiálama?

**Comment by honzajavorek** [comment]
Ano, tak nějak.

**Comment by encukou** [comment]
Pryč s tím tedy!
