### ISSUE TITLE
Naučit Pyvec víc spolupracovat s PSF/python.org

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#21]
Na Pycon US byl nejaky talk o srazech a byl tam zverejnen i odkaz na mailing list poradatelu srazu. @kvbik  bude vedet vic, ale je to pravděpodobně https://mail.python.org/mailman/listinfo/group-organizers

Navíc existují oficiální kalendáře PSF, kam lze hlásit svoje akce a je to pak v celosvětových kalendářích atd. https://wiki.python.org/moin/PythonEventsCalendar
### Cíl

Propojit se - dostat se do mailinglistu, zjistit, jestli tím nemůžeme nějak pomoci našim srazům. Zároveň mít účast na https://wiki.python.org/moin/LocalUserGroups#Czech_and_Slovak, http://python.meetup.com/.

Přečíst https://wiki.python.org/moin/StartingYourUsersGroup, mít českou verzi na python.cz nebo někde, umět tyto informace využít pro naše srazy - co takhle #5 ?

Dostat PSF logo na pyvec.org a dostat se jako neziskovka na PSF radar.

**Comment by lspdv** [comment]
Zda se, ze uz na tom nebude tolik prace - nekdo ji udelal za nas?
<img width="1434" alt="screen shot 2017-02-01 at 21 54 13" src="https://cloud.githubusercontent.com/assets/12471149/22525859/4f498088-e8c9-11e6-8830-cf112c8faba4.png">
<img width="1440" alt="screen shot 2017-02-01 at 21 55 40" src="https://cloud.githubusercontent.com/assets/12471149/22525860/4f49cd22-e8c9-11e6-98e9-5a61827a481d.png">

**Comment by honzajavorek** [comment]
@hroncok pokud k tomuto něco máš, napiš to sem.

**Comment by hroncok** [comment]
Co jsem zjistil na sprintu:

 * není ze strany PSF žádoucí, aby byl Pyvec working group PSF
 * jako jednotlivci můžeme být Contributing members

(S cílem této issue to moc nesouvisí, ale píšu to sem, abychom to věděli)

**Comment by honzajavorek** [comment]
Podle mě by cílem issue mohlo být doplnit do Zapojse na python.cz informace o tom, jak se stát členem PSF a že to mají lidi dělat a co tím mohou získat a k čemu to je. Co vy na to? Mohl by to být dobrý první krok.

Jinak bych to viděl na mírnou duplicitu s #5. To s tím kalendářem srazů bych asi úplně neřešil. V seznamu jsme a abychom registrovali každý event co u nás bude, to si asi necháme někdy až po https://github.com/pyvec/python.cz/issues/220.

**Comment by honzajavorek** [comment]
Zavřu ve prospěch https://github.com/pyvec/python.cz/issues/221.
