### ISSUE TITLE
onlinestars.cz nás chtějí jako účastníka

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#22]
http://onlinestars.vimvic.cz/ - rádi by, abychom přišli na jedno vydání a povykládali o Pythonu a Python komunitě. Spíš biz přednáška.

**Comment by lspdv** [comment]
To je fajn, prijdu delat fandu!

**Comment by aleszoulek** [comment]
Copak prijit a povykladat.

Tady bude nejdulezitejsi vymyslet dobrej "biz" obsah. Mas nejakou
predstavu, jaky lidi tam chodej?

A.

**Comment by encukou** [comment]
Máme tu někoho, koho by bavilo udělat biz přednášku? Nebo je to potřeba pro větší slávu Pythonu?

Jestli ne, tak bych to zavřel.

**Comment by honzajavorek** [comment]
Já k tomu mám asi nejblíž, ale teď se mi to dělat nechce. Zavřu to a kdyby náhodou měl někdo zájem, tak se to může znova otevřít.
