### ISSUE TITLE
Rozjet hackatony a workshopy

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#23]
- Django sprinty
- hackatony na drobné utilitky, které posunou český Python vpřed
- hackatony na drobné osobní projekty...
- na různé knihovny, nástroje v Pythonu, atd.

V zásadě se jedná o to vybrat téma, připravit si to trochu, datum, zajistit místnost s internetem a pizzou a pozvat lidi :)

---

Idea: Proc je tezke udelat jine workshopy nez treba DG je i proto, ze neexistuji predpripravene materialy. To lze vyresit:

a) materialy vytvorit
b) materialy najit

Proc bychom delali a) ? Mozna neexistuje nejaky celosvetovy souhrn materialu pro Python workshopy ala pyvideo, ale muzeme si je vyhledat individualne (na group-organizers mailinglistu se individualne obcas nejake objevily), forknout, prelozit, neprelozit ale rozsirit, kontaktovat autory. Porad imho do budoucna lepsi nez si to vytvorit na kolene, navic je to contributions-friendly. Dalo by se to udelat taky do GitHub "knizek" jako to maji u DjangoGirls.

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/aedmELXs/25-rozjet-hackatony-a-workshopy).

**Comment by honzajavorek** [comment]
@lspdv Možná se pletu, ale tenhle úkol by tě možná mohl zajímat?

**Comment by honzajavorek** [comment]
Online kurzy - motivovat nějak lidi, aby dělali Python kurzy třeba na naucmese.cz atd.? Nebo rovnou udělat partnerství s naucmese.cz, že díky Pyvci bude nějak výhodnější, aby člověk udělal kurz na nějaké téma o Pythonu? Jen nápady.

**Comment by honzajavorek** [comment]
Online kurzy - motivovat nějak lidi, aby dělali Python kurzy třeba na naucmese.cz atd.? Nebo rovnou udělat partnerství s naucmese.cz, že díky Pyvci bude nějak výhodnější, aby člověk udělal kurz na nějaké téma o Pythonu? Jen nápady.

**Comment by lspdv** [comment]
to zni jako ukol pro me :)

**Comment by honzajavorek** [comment]
@lspdv sem tě přidal do Pyvce, tak až to přijmeš, přiřaď se sem jako osoba vykonávající 😄

**Comment by zuzejk** [comment]
vypadá to, že nejmenovaná firma v Brně by nám chtěla nabídnout prostory, snad i s občerstvením, poprosila jsem je o upřesnění nabídky. To jen aby to nezapadlo, když se moje issue o nabídkách sponzorů nerozvíjí...

**Comment by honzajavorek** [comment]
Já mám pocit, že tohle můžeme zavřít. Issue je vágní a aktivity v tomto směru už se dějí, minimálně v podobě NePyva a PyWorkingu. Z původního popisu issue není úplně jasné, co bylo cílem. Video kurzy mají vlastní issue #18. Materiály se shromažďují na http://naucse.python.cz/.
