### ISSUE TITLE
Vytahat z Facebooku informace o starých brněnských Pyvech

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#26]
### Situace

Informace o starých brněnských srazech jsou roztroušené po Facebooku a Srazy.info (které se nyní už ani aktivně nepoužívají). Chtěli bychom je mít v jednom archivu na Lanyrdu.
### Co je Lanyrd?

Lanyrd je "wiki" na srazy a konference. Kdokoliv může na čemkoliv dělat změny. Brněnské srazy jsou k nalezení zde: http://lanyrd.com/series/brno-pyvo/
### Kde najdu stará data?

Na Srazy.info lze najít informace zde: http://srazy.info/brnenske-pyvo/terminy/

Na Facebooku jsou to tyto události:
1. https://www.facebook.com/events/196576713713338/ (Apr 2011)
2. https://www.facebook.com/events/178935428828137/ (Jun 2011)
3. https://www.facebook.com/events/232475156798546/ (Sep 2011)
4. https://www.facebook.com/events/173703669376237/ (Oct 2011)
5. https://www.facebook.com/events/194048420671473/ (Nov 2011)
6. https://www.facebook.com/events/266397403422488/ (Jan 2012)
7. https://www.facebook.com/events/197931570315648/ (Mar 2012)
8. https://www.facebook.com/events/256834891079598/ (Apr 2012)
9. https://www.facebook.com/events/444292668942770/ (Sep 2012)
10. https://www.facebook.com/events/366769300072423/ (Oct 2012)
11. https://www.facebook.com/events/373704196044634/ (Nov 2012)
### Co je potřeba udělat?

Projít stará data a vše, co má nějakou hodnotu (jména přednášek, přednášejících, slajdy, atd.) přidat do historických událostí na Lanyrd.

**Comment by encukou** [comment]
s/Lanyrd/[pyvo-data](https://github.com/pyvec/pyvo-data)/
