### ISSUE TITLE
Pyvec na Google+

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#28]
Zjistil jsem, že máme Google+ stránku 😱

https://plus.google.com/+PyvecOrg/posts

Já teda třeba G+ vůbec nepoužívám. Otázka je, co s tím. Chce to někdo udržovat? Máme to smazat nebo tam nastavit přeposílání tweetů :trollface: nebo co? Nápady?

**Comment by vlinhart** [comment]
jsem pro zahozeni a smazani.. tech soc siti je trochu prilis..

**Comment by frenzymadness** [comment]
Přesně tak. Google+ je taková ta vesternová krajina s dvěma supy a valícím se senem, kde nikdo není.

**Comment by encukou** [comment]
Nebylo by lepší tuhle diskusi vést tam, ať se ozvou lidi kterých se to týká?

**Comment by vlinhart** [comment]
Navrhuju tam teda vrazit status neco jako. 

> Vzhledem k tomu, že G+ používá málo lidí a nemáme síly na jeho aktualizace, tak navrhujeme jeho zrušení. Pokud s tím nesouhlasíte, zareagujte tady prosim.

**Comment by aleszoulek** [comment]
Zajimalo by me, jestli byse to nemohlo hodit na nejaky SEO, ci tak neco... Jakoze kdyz se neco hleda a je pro to G+ stranka, jestli google nedela nejakou magii. Ale souhlasim, ze 2 roky bez udrzby je naprd..

Kdyby to umelo nejak automaticky postovat eventy, ktery pyvec organizuje, tak by to stalo myslim za udrzeni.

**Comment by frenzymadness** [comment]
Na Google+ má Pyvec celkem **0** příspěvků a celkem **4** sledující uživatele, z nichž tři byli o víkendu na sprintu (včetně mě). Nejsem si jist, zda je vůbec co řešit. Zrušením této stránky bez příspěvků nikdo o nic nepříjde.

**Comment by honzajavorek** [comment]
No problém automatického postování je v tom, že to pak někdo začne používat a třeba napíše komentář "kde přesně se to dneska koná?" a nikdo mu neodpoví, žejo. Můžeme to nechat jako stránku, která v podstatě jen vede na naše weby. Nevím. Taky by asi chtělo, aby tohle dořešil člověk, který má přístup na tu Pyvec stránku, protože to já nejsem (nemám vůbec ani G+ účet).

**Comment by aleszoulek** [comment]
<img width="462" alt="screen shot 2016-08-22 at 1 28 21 pm" src="https://cloud.githubusercontent.com/assets/270768/17853376/69b8ada0-686c-11e6-8713-3de20d945270.png">

Ja tam teda vidim 38 sledujicich.

Neberte me jako silenyho advokata G+, jen mi prijde, ze 38 neni uplne malo lidi, ktery bych jen tak zahodil..

Souhlasim s automatickym postovanim, mozna tam jde nastavit nejaka notifikace, aby spravce stranky o komentu vedel? Nezkousel jsem.

Jinak ja k ty strance admin pristum mam

**Comment by frenzymadness** [comment]
@aleszoulek Aha, on je tam totiž z nějakého důvodu Pyvec dokonce dvakrát:
1. https://plus.google.com/u/0/113554359274381095989/posts - 4 fanoušči, 0 příspěvků, 82371 zobrazení
2. https://plus.google.com/u/0/+PyvecOrg/posts - 38 fanoušků, hodně příspěvků, 14471 zobrazení

Tak to zcela mění situaci. I když ten počet zobrazení jde úplně proti aktivitě dané stránky.

**Comment by lspdv** [comment]
Ou maaan, tehle siti uz je nejak moc. A tady je presne videt, ze pyvec nema cloveka, ktery dela administrativu, sponzoringy vyjednava a site udrzuje!

Vsechno bych to smazala! :speak_no_evil:

**Comment by honzajavorek** [comment]
Je rok 2018 a já neznám už jediného člověka, který to aktivně používá. Než jsem napsal tento komentář, tak jsem se musel podívat, jestli vlastně G+ ještě existuje.

Máme na G+ dvě stránky Pyvce a nevidím důvod je tam mít. Nevidím ale ani důvod se zabývat jejich rušením. Pokud na té sociální síti nikdo není, nikdo je tam neobjeví. Kdo je objeví, tak si snad všimne, že je nevyužíváme a je to jen nějaký náhrobní kámen dob minulých. Za mě je zbytečné vynakládat energii tímto směrem.

**Comment by encukou** [comment]
Jen pozor jestli ten G+ účet není nějak svázaný s YouTube – matně si vzpomínám že Google se tenkrát snažil  centralizovat info o lidech na G+, a YT do toho jaksi zatáhl.

**Comment by encukou** [comment]
> Je rok 2018 a já neznám už jediného člověka, který to aktivně používá.

FWIW, Google už jich taky moc nezná, tak se rozhodli [Google+ do roka zaříznout](https://www.blog.google/technology/safety-security/project-strobe/).
