### ISSUE TITLE
Dokončit převod pyvo.cz do rukou Pyvce

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#3]
Stav: platím za pyvo.cz, mám nad ním plnou kontrolu, ale doménový kontakt stále není na mě. Doménový kontakt je na @michaljanik, ale problém je, že abychom ho převedli na Pyvec, je potřeba chodit na poštu a kdo ví kam ještě, aby se to převedlo, což se nechce @michaljanik (protože už to jednou v minulosti nevyšlo). Rádi bychom se vyhnuli potřebě chodit někam na poštu a našli způsob, jak doménový kontakt převést jen klikáním na internetu.

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/CDkLNCfm/50-dokoncit-prevod-pyvo-cz-do-rukou-pyvce).

**Comment by honzajavorek** [comment]
@sairon přiřaď se sem prosím až budeš v Pyvec organizaci

**Comment by honzajavorek** [comment]
Tak se @sairon se to nepovedlo a pak odešel z CZ.NIC, takže ho nahradím @zoellenka 😄 Včera měla nějaký tip, jak to dořešit. Údajně by se to mohlo dát převést na registrátora, který papírování nevyžaduje. @zoellenka, jak to funguje přesně? Můžeš nám s tím pomoct?

Možná by nám s tím mohl pomoci i @paveldedik, mrk mrk? 😉

**Comment by paveldedik** [comment]
Upřímně vůbec netuším, jak bych s tím mohl pomoct. Pokud však budu vědět jak a nebude to vyžadovat nepřiměřené úsilí, tak pomůžu :-)

**Comment by honzajavorek** [comment]
Pokud bychom vymysleli způsob, jak nenáročně převést ten doménový kontakt, tak bych tě chtěl poprosit, aby ses u nás přimluvil a aby to Michal s námi ještě jednou po letech zkusil a zkusili jsme to převést a dokončit. A pokud to stejně nepůjde jinak než přes nějaké chození na poštu, tak bych tě poprosil vlastně o totéž, ale možná to bude už nepřiměřené úsilí 😄

**Comment by MichalJanik** [comment]
Hmm. Tak to pojďme kusit. Já k té doméně už vlastně přístup (asi) vůbec nemám. Zkusil jsem nyní zadat převod do Weodsu a ten mi píše, že už u něj evidována je. Předpokládám, že je pod nějakým Vašim ůčtem.
A tak si říkám, proč nemůžete ty administrativní kontakty změnit Vy? Případně co pro to mám udělat já?

**Comment by honzajavorek** [comment]
Abych měl doménu, potřebujeme podle WEDOSu tři věci:

- [x] převedenou doménu pod můj účet u WEDOSu, abych ji mohl technicky spravovat
- [x] převedené fakturační údaje a placení pod můj účet na WEDOSu, abych ji mohl platit
- [ ] převedené vlastnictví / doménový kontakt, abych s ní mohl nakládat jako se svým majetkem a převáděl ji dál nebo pod jiné registrátory

Když kouknu do administrace, vidím toto:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/283441/29810745-553ca656-8ca1-11e7-8086-bd38182c8fd0.png">

Když kliknu na "kontakt vlastník", je tam:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/283441/29810763-6d19e018-8ca1-11e7-8337-52c25219d77c.png">

Můžu kliknout na "změna majitele" a zkusit zadat svůj kontakt, tedy `WEDOS-BWP-23826`, a dám _Změnu potvrdí původní i nový majitel použitím e-mailu a SMS_:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/283441/29810901-eddbad4e-8ca1-11e7-9726-972103f03f26.png">

A to skončí na chybě:

> Stávající kontakt není registrován u nás. Nejprve je nutné provést přeregistraci kontaktu k nám. Přeregistraci kontaktu můžete provést [zde](https://client.wedos.com/domain/tools/contact-transfer.html?reg=cznic&tld=cz&contact_id=CID:ID120782127970941-MITONCZ).

Takže moje teorie je, že pokud by tvůj kontakt `CID:ID120782127970941-MITONCZ` byl u WEDOSu (což už podle toho ID obsahujícího MITONCZ vypadá, že není), tak to můžeme převést klidně jen SMSkou. Co obnáší převedení kontaktu pod WEDOS, to nemám nejmenší tušení. Jak je vidět z toho screenshotu výše, pokud nelze použít metodu přes SMS, je potřeba úřední dopis.

@zoellenka o víkendu naznačovala, že ten úřední dopis potřebují jen někteří registrátoři a že se to v praxi dělá tak, že se to na chvíli převede jinam, tam se udělá změna majitele, a pak se to převede zpět. Ale co to přesně obnáší a jak bychom to měli udělat, to opět nevím 😞

**Comment by messa** [comment]
@honzajavorek Informace raději dohledávej na https://www.nic.cz/whois. Třeba ten kontakt s MITONCZ na konci je u registrátora REG-STABLE. Kontakt by se měl dát na wedos převést zde: https://client.wedos.com/domain/tools/contact-transfer.html?reg=cznic&tld=cz
To tlačítko "zaslat heslo" způsobí to, že CZ.NIC pošle e-mail s heslem na e-mailovou adresu o toho kontaktu.

**Comment by frenzymadness** [comment]
Když jsem se staral o velké množství domén, řešili jsme to celkem často. Vše jsme měli registrováno u Ignumu a ten požadoval úředně ověřený podpis pro změnu vlastníka, ale dalo se to obejít a udělat od stolu. My jsme postupovali takto:
1. Nejprve je třeba změnit registrátor na nějakého, který nevyžaduje úředně ověřený podpis pro změnu vlastníka. Mě se v tomto osvědčil Active24 a podle všeho to tak stále funguje [0]
    1. Pro změnu registrátora je potřeba u toho současného vygenerovat tzv. AUTH-ID. Toto heslo může vygenerovat jen současný registrátor, má platnost jen 24 hodin a obdrží jej současný majitel na email vedený u domény.
    2. Když AUTH-ID máš, můžeš snadno změnit registrátora na Active24 buď přes svůj již exitující účet nebo skrze objednávku, při které si účet vytvoříš. [1]
2. Když je doména registrovaná u Active24, je možné u ní provézt změnu majitele a celé ověření proběhne jen skrze email současného a nového vlastníka.
3. Pak je třeba naprosto stejným postupem změnit registrátora zase zpět v tomto případě na Wedos.

[0] https://faq.active24.com/cz/166891-Zm%C4%9Bna-vlastn%C3%ADka-dom%C3%A9ny#zmenadrzitele
[1] https://faq.active24.com/cz/807961-P%C5%99evod-dom%C3%A9n-k-Active24

**Comment by MichalJanik** [comment]
Zkusil jsem si nechat poslat to heslo. Wedos píše:
![mergado](https://user-images.githubusercontent.com/608857/29818664-b935650a-8cbd-11e7-981a-e5e9922f651d.png)

**Comment by MichalJanik** [comment]
Kdysi jsem míval domény u Kvapem.cz. Proto to staré ID. Všechno jsem převáděl pryč. Už roky jsem v jejich administraci nebyl. Podle všeho jsem po sobě uklidil docela dobře, protože se nemohu přihlásit (poslat si heslo) na žádný z e-mailů, které mne napadají. A na veřejném webu jsem nic nenašel. Tak tam taky nevím, co dělat.

**Comment by messa** [comment]
@MichalJanik Nechybí v tom formuláři na začátku to `CID:`? Je to normálně součástí identifikátoru, z pohledu registru je to celé jeden string.

**Comment by MichalJanik** [comment]
Zkoušel jsem obě varianty.
Buď to nakonec nějak prorazil někdo z místních dobrodějů, nebo to nakonec něco udělalo, ale hodně dlouho trvalo. Po delší odmlce přišla autorizační SMS a já pokračuji dál.
Teď budeme čekat na ověření dopisem.

Děkuji.

**Comment by honzajavorek** [comment]
My děkujeme!

**Comment by MichalJanik** [comment]
Tak jsem zase problémovej :worried: 
Dopis z Nic.cz přišel. Ověření kontaktu jsem provedl. Pak jsem dumal, co dál a vzpoměl na http://www.domenovyprohlizec.cz/ že by se to dalo třeba použít. Podle návodu jsem šel na ověření z registru a po vyplnění získal toto:

![screenshot-093d8cfc-e6a9-4f43-b8cd-7c4df278f60c-2017-09-03-21-42-06](https://user-images.githubusercontent.com/608857/30006091-c732c9c2-90f0-11e7-93c0-4c2544a2cf25.png)

Zkouším různé varianty a mění se jen text chybové hlášky. Dál mne to nepustí. Přitom když kliknu na odkaz `Zobrazit údaje z registru`, vrhne mne to na https://www.nic.cz/whois/contact/cid%3Aid120782127970941-mitoncz/ a tam je:
![screenshot-093d8cfc-e6a9-4f43-b8cd-7c4df278f60c-2017-09-03-21-44-03](https://user-images.githubusercontent.com/608857/30006106-0840f3d0-90f1-11e7-8bd3-4c5d000dc01d.png)

Což je asi validní vstup, ne?
Tak nevim, něco mi nedochází, nebo je ve formuláři bugísek...?

**Comment by MichalJanik** [comment]
Mno. A nebo to půjde tím postupem, co jsi @honzajavorek psal - jak jsi řádil na Wedosu. Tak prosím vygeneruj tu žádost a já to potvrdím.

A předchozí komentář může skončit spíš jako podnět pro kluky z Nicu?

**Comment by honzajavorek** [comment]
Takže abych shrnul situaci. @messa se přiznal, že ten formulář z CZ.NIC nefungoval kvůli němu:

> hele já se k něčemu přiznám - za tu věc s emailem, sms a dopisem můžu já, někam jsem před týdnem na nic.cz kliknul a tím jsem spustil proces registrace do mojeid. Neměl jsem to v úmyslu, ale když už se to stalo, tak jsem doufal, že to k něčemu bude :slightly_smiling_face: ale pak to @MichalJanik nepustilo kvůli tomu, že identifikátor není validní mojeid username, takže to bylo k ničemu a ignorujte to

Tím můžeme epizodu s nefunkčním CZ.NIC formulářem nejspíš uzavřít. Co se ale povedlo - @messa našel [tento](https://client.wedos.com/domain/tools/contact-transfer.html?reg=cznic&tld=cz) formulář. Jakoby za Michala jej vyplnil, což Michalovi poslalo heslo k přesunu doménového kontaktu k WEDOSu. Michal mi to heslo poslal. Já jsem šel do svého WEDOS účtu a dokončil přesun přes  [tento formulář](https://client.wedos.com/domain/tools/contact-transfer.html?reg=cznic&tld=cz). Tím se mi povedlo docílit následujícího:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/283441/30110279-d3dcbafa-9309-11e7-99a3-aa79d807ef11.png">

Ještě sám nevím, co to znamená, ale teoreticky by to mělo znamenat, že ten kontakt je teď můj a pod WEDOSem. To by teoreticky mělo znamenat, že můžeme zaškrtnout ten třetí bod:

- [x] převedenou doménu pod můj účet u WEDOSu, abych ji mohl technicky spravovat
- [x] převedené fakturační údaje a placení pod můj účet na WEDOSu, abych ji mohl platit
- [ ] převedené vlastnictví / doménový kontakt, abych s ní mohl nakládat jako se svým majetkem a převáděl ji dál nebo pod jiné registrátory

Ale dokud to neověřím, tak tomu neuvěřím! 😂 Každopádně díky všem za spolupráci a za nervy! Je to boj!

**Comment by honzajavorek** [comment]
Takže ještě ne, pokračujeme ve formuláři z https://github.com/pyvec/zapojse/issues/3#issuecomment-325588871. Nyní by nám to mělo poslat potvrzující SMS. Vytvořil jsem žádost o přesun, ale všiml jsem si, že tam mám staré telefonní číslo, takže jsem ji zase zrušil.

Vytvořím novou žádost, až změním číslo. @MichalJanik budu pouze tiše doufat, že tvoje telefonní číslo, co tam vidím, je stále aktuální, ale myslím, že jo.

**Comment by honzajavorek** [comment]
Takže žádost vytvořena, Michale měl by ti přijít e-mail, kde bude odkaz, a SMS, kde bude heslo. Pokud mi tyto dvě informace nějak přepošleš, měl bych být schopen to celé dokončit.

**Comment by MichalJanik** [comment]
Ahoj, přišlo mi jen toto: https://client.wedos.com/domain/owner-confirm.html?id=KRRSSJNMQK&ckey=mfMEXGxR kde `stav žádosti` je `zrušena` :worried:

**Comment by MichalJanik** [comment]
PS: můj mobil je 777 628 156. Kdyby se to hodilo. Je to stále tej stejný.
A ano, použitelnost toho procesu je kapku kostrbatá. Byť můj nevysoký intelekt a nulová praxe tomu pomáhají :worried:

**Comment by honzajavorek** [comment]
@MichalJanik To bude ta první žádost. Nepřišla pak ještě jedna? A na mobil ti nepřišlo nic? Číslo by mělo sedět.

**Comment by honzajavorek** [comment]
<img width="816" alt="screen shot 2017-09-10 at 20 10 37" src="https://user-images.githubusercontent.com/283441/30251653-597e12aa-9664-11e7-9219-023f043b9a03.png">

**Comment by honzajavorek** [comment]
Díky všem zúčastněným! Bylo to náročné, ale jsem strašně rád, že se to povedlo. Teď už jen tedy udělat ten úkol z titulku, tzn. předat doménu do rukou Pyvce. Teď je totiž v mých rukou, stejně jako pyladies.cz #10. Ale to už je čistě můj boj 😅

**Comment by kvbik** [comment]
no teda! to zni naprosto neuveritelne! zaslouzite si vsechny 🎖 🏅 🥇 🥈 🥉

**Comment by honzajavorek** [comment]
Možná tomu nebudete věřit, ale dnešním dnem přešla doména pyvo.cz kompletně do rukou Pyvec o.s. a je registrována a spravována pod Pyvcím účtem na IGNUMu: https://www.nic.cz/whois/domain/pyvo.cz/
