### ISSUE TITLE
Jak oslovit lidi, kteří chodí na sraz přes pyvo.cz?

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#30]
Je hezké, že jsme udělali http://pyvo.cz/, ale problém je, že nemáme jak komunikovat s lidmi, kteří se tam doví o srazu. Změní se místo konání? Smůla. Nějaká aktualita? Smůla. V Brně dost s účastníky komunikujeme na Facebooku, ale lidi na webu nelze snadno oslovit, na stránku nelze snadno něco rychle napsat. Seznam e-mailů účastníků nemáme. Taky se stává, že na FB je X účastníků, ale nedá se teď vůbec odhadovat, kolik lidí přijde, protože spousta lidí chodí díky informacím na pyvo.cz a na FB nebo jiné stránky eventu vůbec nezavítá 😐 

> Nazdar,
> chceme s klukama zajít na PYVO .  Jen si nejsme jisti ze stránky http://pyvo.cz/brno#2016-06-30  jistí kam?
> Takže pls Kam?    Nejlepe adressa.
> Díky!

**Comment by radekholy24** [comment]
Co spáchat nějakou cool mobilní appku? :-D

**Comment by hanpari** [comment]
Fsharpisti používají srazy.info :)
http://srazy.info/fsharping/6578

Proč znovu vymýšlet kolo?

**Comment by honzajavorek** [comment]
No my máme FB, Lanyrd, meetup.com, ... to není vymýšlení kola. Je to o tom, jak oslovit lidi, kteří nic z toho nepoužívají.

**Comment by hanpari** [comment]
No, pak je řešení reference. :) 
Neříkat na srazu místo setkání, ale stránku, kde budou podrobnosti, které podléhají změnám :)

**Comment by frenzymadness** [comment]
@honzajavorek řekl bych, že se v tomto případě jedná hlavně o problém jednoho konkrétního termínu, který měl oproti všem ostatním nastaveno jako místo konání jen Brno a proto se špendlík na mapě ukazoval uprostřed města namísto skutečného místa konání. Narazil jsem na to samé v červnu, kdy jsem na Pyvu v Brně byl a @encukou to pak ještě v den srazu opravil.

Nicméně nějaký způsob jak lidi notifikovat y se samozřejmě hodil. Otázkou je, jak na to, když je těch komunikačních kanálů tolik.

**Comment by encukou** [comment]
V Brně je FB, v Praze Lanyrd/maily, v Ostravě myslím srazy/FB. Kolo se nevynalézá. Problém spíš je že je těch kol moc, a občas se organizátoři vymění nebo začnou používat jiné kanály.
Problém je obecnější – jak notifikovat lidi, co nepoužívají právě tu sociální síť kde jsou organizátoři? 
Když tam dáš referenci, je to k ničemu – kdo nemá účet (nebo se jen nepřihlásí na event) na té správné síti která se pak aktualizuje, notifikaci nedostane.
Chceme aby se lidi _museli_ někde registrovat, aby se to pak orgům líp počítalo? Protože jinak notifikaci holt nepošleš.

**Comment by radekholy24** [comment]
A RSS už nefrčí? To by si mohl každý odběratel nastavit, jak potřebuje. Nebo... Jsme všichni programátoři. Tak zveřejnit nějaké REST API a případně WebSocket API a je to :-) Já vim, asi to přehánim, ale mně se ten nápad líbí O:-)

**Comment by encukou** [comment]
RSS feed na pyvo.cz je. Je tam i iCal. Obojí by se [dalo vylepšit](https://github.com/pyvec/pyvo.cz/issues/21), ale jako kanál kterým budou všem zaručeně chodit notifikace se nedá použít ani jedno. A to ali nemluvím o odhadování počtu účastníků.

REST ani WebSocket tam není, "API" je repozitář v Gitu. Pull requesty vítány, ale problém to pravděpodobně nevyřeší. Ne všichni, kdo chodí na Pyvo, jsou programátoři. A ne všichni programátoři si rozumí s REST API a WebSockets...

**Comment by radekholy24** [comment]
Jasně... Předpokladem bylo, že ti účastníci Pyva, co jsou programátoři a rozumí si s REST API a WebSocket API, použijí/napíší nějakou aplikaci, která to bude využívat. A předpokládá se, že ta aplikace bude open source a dostane se tak i k těm, co si jí sami napsat nemohou... Ale byl to jen nápad...

**Comment by honzajavorek** [comment]
Možná tady řešíme špatný problém. Možná by stačilo vyřešit https://github.com/pyvec/zapojse/issues/27 jako příčinu a je to.

**Comment by encukou** [comment]
Jo, synchronizovat všechny kanály mi přijde jako jediné schůdné řešení.
Neřeší to ale lidi, co se podívají _jenom_ na pyvo.cz, a taky to moc neřeší odhad účasti.

**Comment by honzajavorek** [comment]
Já mám obavu, že tohle řešení nemá a je to nakonec asi okrajový problém. Jediný způsob relativně spolehlivých notifikací pro lidi, kteří nesledují sociální sítě, je e-mail. V tom případě chceme mít na pyvo.cz nebo python.cz sběr e-mailových adres a posílat mail, když se updatují informace o Pyvu. Přijde mi ale, že je to kanón na vrabce a je to znovuvynalézání nějakého meetup.com. Časem bych sbíral maily na #11 / #39, ale řešit notifikace k Pyvům mi asi přijde málo muziky za hodně programování. Issue zavřu, ale pokud má někdo námitky, pište.
