### ISSUE TITLE
Tržiště práce

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#35]
Udělat dedikovaný job board? Nějaký inteligentni monitoring nabidek prace a jejich agregace a analyza - jobs, startupjobs, facebook pyonieri, django-cs, konference py?

**Comment by radekholy24** [comment]
Zahrnul bych i poptávku...
Idálně bych se rád našel v nějakém katalogu českých Pythonistů, kde by si mě třeba mohl někdo najít :-)

**Comment by honzajavorek** [comment]
@PyDeq tak na to uz je https://github.com/pyvec/python.cz/issues/139, samozřejmě to souvisí

**Comment by radekholy24** [comment]
Oops, přehlédl jsem.

**Comment by nait-aul** [comment]
Za mě ze začátku včetně monitoringu startupjobsu.cz a jobsu.cz, do budoucna ideálně bez nich. 

Jinými slovy aby vlastní dedikovaný job board byl hlavním platformou personalistů pro nábor Pythonistů a penízky za inzerci šli řaději do kapes Pyvce, než těm dvěmá firmám (samozřejmě by šlo udělat výjimky pro čerstvě založené firmy / startupy a tak).

Co jsem si tak poslední dobou všiml, tak u startupjobsu jsou třeba inzerárty, které nemaj s Pythonem nic společného, jen to prostě personalisté naprali do více kategorií a u jobsu pak, že primární náplní práce je Java / C# a Python je tam zmíněn jen jako bonus nebo ani to ne (např. výpis všech klíčových slov z IT :smile:).

\+ jsem také pro za poptávku

**Comment by nobodyguy** [comment]
Mám scrapování StartupJobs.cz, prace.cz a jobs.cz + ukládání do mongoDB (nebo kamkoliv jinam), je to napsané za použití Scrapy. Chtěl jsem udělat i zasílání relevantních nabídek subscribnutým lidem na určité tagy, ale to zatím nemám technicky namyšlené, aby to bylo nějak rozumně a efektivně udělané.
Během dneška hodím link na repo.

**Comment by nobodyguy** [comment]
https://github.com/nobodyguy/jobot
Je to spis takovy pracovni prototyp.

**Comment by honzajavorek** [comment]
Super! Mě tohle téma strašně zajímá, ale nejsem teď schopen se mu před PyConem věnovat. Nenech se zdržovat, vytvoř prototyp, repozitář ti klidně dáme tady na Pyvec a zkus to nějak rozjet. Jak budu mít nějakou energii, mrkneme na to a zakomponujeme do python.cz třeba.

**Comment by honzajavorek** [comment]
Svoje job boards mají už i jednotlivé JS frameworky - https://vuejobs.com/?ref=vuejs Možná by stálo za to s tímhle pohnout.

**Comment by honzajavorek** [comment]
Probrali jsme to na sprintu u ohně a závěry jsou následující:

- Mít job board pro Python v ČR na python.cz by bylo fajn, ale to je tak všechno. Momentálně lidi z HR mají kam posílat nabídky a programátoři mají kde je číst. Skupina Pyonieri na Facebooku žije inzeráty, ale zatím nám nepřijde, že jich je příliš mnoho. Udělat dedikovaný job board by umožnilo tuto věc podchytit, centralizovat, něco na inzerátech vydělat pro Pyvec (inzeráty pro juniory by byly zadarmo) a vyčistit tím trochu skupinu Pyonieri. Ale to by bylo tak všechno.
- Co je ale nutně potřeba a je to reálný problém, je job board pro nabídky práce pro juniory. Toto by velice uživily především PyLadies. Druhá věc je, že tyto nabídky by nemysely být jen na Python, juniorní PyLadies berou všechno, co se hodí pro juniory. Samozřejmě čím blíž ke komunitě, tím líp, ale rozhodně by nemělo smysl to omezovat jen na Python. Třeba i Apiary otevíralo juniorskou pozici, je to v podstatě firma spřátelená s komunitou, ale pozice byla na JavaScript.

Dohodli jsme se, že by tedy mělo smysl udělat job board na nabídky dedikované začátečníkům. Ten dáme někam na web pyladies.cz. V podstatě by to mělo být na bázi jednoho vyladěného formuláře a jedné stránky, kde se to bude zobrazovat. Jako backend by byly Google Spreadsheets, kde může kdokoliv nabídky administrovat (upravovat, expirovat, ...) jednoduchou klikačkou. Jako zpracovatelé tohoto nápadu jsme se nabídli @messa a já. Člověkem, pro kterého to budeme primárně dělat a kdo bude věc asi nejvíc používat, je momentálně @zuzejk.

Do budoucna můžeme naznat, že job board funguje a má smysl i pro ten python.cz a můžeme ho tam udělat, ale zatím nás to nepálí a nebudeme to řešit. Proto zatím https://github.com/pyvec/python.cz/issues/209 zavřu.

**Comment by honzajavorek** [comment]
Pracuji na řešení. Až jej opensourcuji (což bude chvíli trvat), mělo by se to tady zavřít.

**Comment by encukou** [comment]
@honzajavorek, [junior.guru](https://junior.guru) sice není jen o Pythonu, ale myslím že to splňuje zadání dost na to, aby se to tu zavřelo. Co myslíš?

**Comment by honzajavorek** [comment]
Ano, vzniklo vyloženě jako pokus o řešení druhého bodu v https://github.com/pyvec/zapojse/issues/35#issuecomment-325124547
