### ISSUE TITLE
Anketa mezi účastníky Pyva?

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#36]
Mohli bychom udělat nějakou velkou anketu mezi účastníky Pyv o tom, co je zajímá, co se jim líbí, jaký koncept Pyva se jim líbí, co jim chybí, co by se jim líbilo víc, atd. Jenže by se to muselo nějak dobře seskládat, aby na základě toho šlo něco zjistit, vyfiltrovat to podle města a tak. Hodilo by se to organizátorům srazů.

**Comment by lspdv** [comment]
Nemuzu si vzpomenout, jak se jmnuje ta sluzba, co pouzivali na PyCon SK jako na otazky behem talku. Mela jsem pocit, ze to pouziva i ImpactHub a ze by se to dalo pouzit i na tohle?

**Comment by honzajavorek** [comment]
https://www.sli.do/ ? to by mozna slo nejak vyuzit!

**Comment by lspdv** [comment]
jooo tajto, to je ono. diky, prozkoumam ho, jestli to maj uz tak vymakany,
ze by to tam slo nejak filtrovat potom

2016-08-22 14:01 GMT+02:00 Honza Javorek notifications@github.com:

**Comment by lspdv** [comment]
Tak bohuzel, mne se to nezda pouzitelne. Zkusim hledat dal.

**Comment by honzajavorek** [comment]
Mozna by stacil i google form klasickej, ale museli bychom vymyslet, jaky
otazky (a jak polozeny) davaji smysl, aby z toho byly nejaky odpovedi, co
nas posunou dal.

**Comment by lspdv** [comment]
To by mozna resilo. Protoze se tam da dat otazka odkud jsi - das na vyber
pevne moznosti - pak z toho udelas tabulku na docs.google jednim klikem a
tam uz se to da filtrovat. No a pokud to bude z pevnych odpovedi a ne ze ti
nekdo napise Praguska a nekdo Krno, tak uz se to da. S tim uz zkusenosti
mam.

2016-08-24 13:52 GMT+02:00 Honza Javorek notifications@github.com:

**Comment by honzajavorek** [comment]
Muze nas zajimat, jestli ten clovek dojizdi. Tzn. nez odkud jsi dat "na
ktere pyvo pravidelne chodis" (s moznosti zaskrtnout, ze nechodi pravidelne
na zadne) a pak dat otazku odkud je. Tim muzeme zjistit, kde by treba
nebylo od veci pyvo zalozit. Nebo ze spousta lidi na, ted si vymyslim,
brnenske pyvo, dojizdi nekde z okoli, tak by bylo lepsi ho posunout k
nadrazi.

**Comment by lspdv** [comment]
Jelikoz vidim, jak nam to jde zase vsechno pomaleji, tak bych ti treba hodila nastrel a ty to pak doupravis podle sebe. Bo se jinak nedockame! :-) a ja su nedockava haha!

**Comment by lspdv** [comment]
Jestli se dostanu primo do slozky Pyvce, coz mi moc neprijde, asi mam pristup jen do holcickovsky slozky, tak bych to tvorila rovnou tam. Nebo to tam presunu.

**Comment by honzajavorek** [comment]
Doladil jsem to dnes. Ještě jednou to projdu a pak to zkusím předložit dalším orgům a uvidíme, co z toho bude.

**Comment by kvbik** [comment]
pridavam linky na pribuzna issues #11 #30 #39 - jakoze, resi se to, tak at to nezapadne.
