### ISSUE TITLE
Společný Google form pro sběr emailů

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/zapojse#39]
Napadlo mě vytořit společný Google formulář pro sběr emailů od lidí okolo Pythonu v ČR. Mohl by z toho být centrální mailing list s možností filtrace dle zájmu každého soudruha :smile:

Kdo by pak chtěl poslat nějaký hromadný mail, vyfiltroval by si jen zainteresované lidi. 

Například něco jako:
- Emailová adresa:
- Mám zájem o maily o:
- Pythonu a vše kolem něj (newsletter https://github.com/pyvec/zapojse/issues/11)
- PyConu
- Vše kolem Pyva (https://github.com/pyvec/zapojse/issues/30)
- Nabídkách práce pro Python developera (https://github.com/PyLadiesCZ/pyladies.cz/issues/105)
- Pyladies
- ... cokoliv dalšího

Další možnost je pro toto i jiné případy použít nějakou službu k tomu určenou. Mám na mysli něco jako MailChimp nebo ecomail.

Co Vy na to?

**Comment by aleszoulek** [comment]
Rozhodne jsem za vybudovat nejaky python adresar, idealne s mailing preferencema.. Meli jsme nekolik pokusu na prg-pyvech, ale asi jsme to nikdy poradne nedotahli...

Idealne mit pak na tenhle signin formular hezkou url ( http://python.cz/informuj-me ). Samotny rozesilani (aspon casti o pyvech) by mohlo byt soucasti #27

**Comment by honzajavorek** [comment]
@lspdv bude tohle myslim resit konkretne pro PyLadies, tak ji tady jen tak pristouchnu.

Aby lidi mohli ty preference nejak menit, tak by to chtelo uz nakej Mailchimp na to a s tim ja treba vubec neumim, ale pokud si to nekdo veme na starost, budu moc rad! Taky kuk na #11. Formular na sber klidne udelam soucasti python.cz i pyvo.cz, ale o ten backend (newsletter management) se starat nechci. A nema smysl to programovat, kdyz to uz nekde je a staci to treba zaplatit.

**Comment by honzajavorek** [comment]
Mimochodem by tam klidne mohla byt natvrdo kategorie #35. Lidi by mohli dobrovolne odebirat, kdyz by hledali praci a my bychom mohli firmam zpoplatnit kdyz tam neco budou chtit hodit => tim by jsme treba rovnou vydelali na provoz toho mailchimpu.

**Comment by lspdv** [comment]
Jako lspdv to resi, ale obava se, ze vase predstava je vic programmer level. My koukaly na sprintu se zuzejkem na sluzbu kde lidi napisou mail, nam se to sbira do ty sluzby jako list a primo z ni pak rozesilat informacni emaily, pricemz adresa je potom skryta, takze misto moji se tam pak zobrazi PyLadies Praha a nejakej nesmysl adresa. Nevyhoda je v tom, ze to pry zezacatku automaticky pada filteru do promo akci a na seznam.cz do hromadnych apod. U me to ale resilo, ze si nebudu zaplacavat mail. Melo jit o informacni emaily pouze na ktere se neda odpovedet. Muhehee. Jak  vypada odber jsme zkouseli s Josefem tady https://tinyletter.com/stlk

Pokud je to potreba ale uz i pro python.cz nebo pyvo.cz asi by stalo za to uvazovat, zda by to byly schopne naprogramovat Advanced PyLadies a kdo by si nasel cas jim s tim pomoci ;-) 

Jo a ted ctu, ze Javor neco, ze nema smysl to programovat. Toz mozna bych se mohla vic zamerit co dalsiho krom Tinyletter jeste je a dam vedet

**Comment by honzajavorek** [comment]
Ono se to nemusi programovat, to je presne ten MailChimp apod., ono se to
musi jenom zaplatit a pak se tomu venovat :-D

**Comment by frenzymadness** [comment]
Není mezi námi někdo, kdo umí používat ten MailChimp? Měly by tam jít vytvořit vlastní formuláře pro sběr emailů, ve kterých by se dalo rozlišit, zda má člověk zájem o newsletter, nabídky práce atp. a podle toho pak cílit odeslané emaily.

**Comment by lspdv** [comment]
Muzu se o to zajimat a naucit se to. To zvladnu. :D

**Comment by honzajavorek** [comment]
@zuzejk Jak tohle dnes řešíte v PyLadies? Kde uchováváte seznam e-mailů (mailchimp? google docs?) a jak řešíte kdo chce dostávat jaké e-maily? Že bychom to udělali stejně i pro obecný Python mailinglist.

**Comment by frenzymadness** [comment]
Za Ostravu si udržuji mailing list v google sheetu, odkud si je vždy vezmu a odešlu nějakou novinku. Zas tolik jich nemáme, takže to stačí. Občas to merguju se společným sběrným formulářem.

**Comment by encukou** [comment]
Newsletter je #11. Preference nebo jiné newslettery jsou možné, až/jsetli se to udělá :)
Sběr e-mailů přes Google Form v době GDPR rozhodně dělat nechceme.
Zavírám.
