### ISSUE TITLE
Doladit zpracovávání videí ze srazů

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#4]
Když natočíme video, mělo by být zcela jasné, kam je potřeba jej nahrát, kdo a jak jej zpracuje a kam se nahraje. V současné době v tom vládne podivný zmatek, popřípadě nečinnost.

Jediné, co nám jde díky @encukou dobře, je nahrávání. Část videí z Brna má @honzajavorek někde na disku, část se zpracovala přes Martina Bakeše, ale nějak se to nedodělalo a teď to visí ve vzduchu.

Souvisí také s https://trello.com/c/q7dT6LwM/24-nastroj-na-automatizovane-nahravani-videi-na-youtube

**@encukou: Videa jsou zpracovávána; trello zde: https://trello.com/b/D7UXcudE/videa
Uvítám pomocnou ruku, ale zájemce nejlíp zasvětím když si vezmou notebook na Pyvo.**

---

@encukou Část je u mě na disku.

Další věc, kterou bych velice rád outsourcnul na někoho jiného, nebo aspoň si vzpomenul udělat přímo na sraze, je doplňování informací o přednáškách na pražský Lanyrd. Dohledávání jmen z videí mě moc nebaví :)

---

@kacer: Tip ze včerejška: nachystat nějaký ověřený postup, jak zařídit nahrávání obrazovky, předem odchytit přednášejícího a zprovoznit mu to. Nejspolehlivější je asi ale nějaká krabička, co se strčí na kabel mezi noťas a projektor (nehrozí problémy s nekompatibilitou OS, nevzniknou komplikace pokud někdo používá speaker view v powerpointu).

Ale není to levné, např. https://www.czc.cz/avermedia-ezrecorder-130-capture-box-nahravaci-strihova-karta/158193/produkt?gclid=CjwKEAjwqdi7BRCL6Zmjk5-rsTwSJABmrVabbGE7jr2VkhTs0LAVw6qYaO-LLUk5lEZwC78fQd1r1hoCYjzw_wcB

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/m3GCpgwR/13-doladit-zpracovavani-videi-ze-srazu).

**Comment by encukou** [comment]
Mám krabičku. Postprocessing zatím ale stále stojí.

**Comment by encukou** [comment]
Díky `oskar456` vznikla [dokumentace](https://github.com/pyvec/guide/pull/10) a bus factor vzrostl na 200% původní hodnoty :)
