### ISSUE TITLE
Akademie

### ISSUE THREAD

**Issue by ghost** [pyvec/zapojse#40]
## Standardizace znalostí a dovedností

Moje představa je se poptat u živnostníků / ve firmách, jak by měl cca vypadat profil Pythonisty uchazející se o práci na pozicích junior / middle a z toho výchazet v akademii (viz níže). Samozřejmě se to bude lišit podle náplně práce.
## Akademie

Jednotné vzdělávací místo, které by zatřešovalo tyto činnosti:
- vzdělávací materiály včetně sbírky příkladů (ať mají lidi co programovat, pokud nemají nápady), které by pokryly očekáváné standardy ve firmách
  - můžů dál rozvést svojí představu, klidně na pyvu v Ostravě v září, pokud bude
- hackhatony a workshopy (#23)
- školení pro firmy / instituce (#9)
- intenzivnější delší kurzy (nejen PyLadies pro holky) alias rekvalifikační kurzy? (šlo by i zafinancovat z Úřadu práce)
### Proč akademie a standardizace?
1. ve firmách třeba nemající čas či lidi (nějaké vlastní školící centrum), aby si zaškolili nováčky / juniory na slušnou / akceptovatelnou / zaměstnavatelnou úroveň nebo zaučili vlatní zaměstnance novým věcem
2. díky standardizaci by zaměstnavatelé věděli, že uchazeč má požadované znalosti a dovednosti + vlastní řešené projekty (ona sbírka příkladů), tak by stálo jemu / jí dát práci -> urychlení náborového procesu
3. novačcí (kluci i holky) by věděli jak na tom jsou, co jim ještě chybí se doučit
4. pokud by akademie byla na velmi dobré úrovni a měla dobré jméno, tak by mohla patřit mezi hlavní náborové aktivity ve firmách -> už žádné stěžování, že nejsou lidi nebo že se sem musí tahat Ukrajinci
5. mohlo by být užitečné i pro middle / seniory, kteří třeba dělají jen weby a chtějí se rychle naučit používat Python i v jiných oblastech

**Comment by encukou** [comment]
Jo, něco takového by mělo vzniknout na [naucse.python.cz](https://github.com/pyvec/naucse.python.cz). Já mám na starosti materiály, začínám od začátečnických. Rád uvítám pomoc někoho, kdo to bude směřovat víc na to co chtějí zaměstnavatelé. A rád se o tom na Pyvu pobavím.

**Comment by ghost** [comment]
Super, budu se těšit. Vemu svoje poznámky / texty co už mám (zatím jen pro vlastní potřebu, nejen pro Python) +  načrtnu diagramy, jak bych to celé viděl já (struktura, organizování aj.).

**Comment by encukou** [comment]
OK!
@Sanqui, chceš se téhle diskuse zúčastnit?

**Comment by honzajavorek** [comment]
Akademie zní super! V podstatě je to další level toho, co teď po kouskách děláme, hlavně s PyLadies. Jenže na další levely potřebujeme další kupu nadšenců ;-)

**Comment by ghost** [comment]
Já jsem IN.

Teď už sice předbíhám před Pyvem a obecně budoucností, ale hodně super by bylo, kdyby akadamie byla na taková úrovni (výsledky, reference), že by to stálo za to udělat o tom přednášku na europython / pycon us / pycon asia aj.

Prostě dostat se do povědímí i ve světě, že bychom mohli zalobbovat u firem sponzorující konference (i ty, které vůbec neznáme), že by mohly vytvořit pobočky (vývojová centra) i u nás v ČR (-> další potencionální donátoři pro Pyvec), protože tu máme akademii (určitě i úzká kooperace s SŠ / VŠ), lidi, Pyvec, Pyvo a pak takový ty byznys věcičky typu poloha, nákladovost atd. Co se týče ajiny u lidí, kteří ji moc neumí ještě, tak na tom se dá taky zapracovat (sefl-lerning, partnerské jazykovky se slévičkou, dotované kurzy od zaměstnavatelů)

"This is my sen." :+1:

**Comment by encukou** [comment]
Jen tomu pojďme říkat jinak; [Python Academy](http://www.python-academy.com/) už existuje.

**Comment by Sanqui** [comment]
Já jsem určitě pro.  Osobně mi jde lépe učit kódění "tváří v tvář" (koučovat), než psát materiály, ale i toho bych se rád účastnil, jen ne vyloženě tvořil :)

**Comment by encukou** [comment]
Super!
Dostaneš se na [Ostravské Pyvo](http://pyvo.cz/ostrava) v září?

**Comment by zuzejk** [comment]
tohleto téma mě fakt hodně zajímá, sama jsem navrhovala něco podobného, akorát nevim, jestli se dostanu na to Pyvo v Ostravě :/

**Comment by ghost** [comment]
Já si až včera všiml, že zářijové ostravské Pyvo nebude tam jako obvykle, tj. v centru Ovy, ale v Beskydech (Ostravice), naštěstí mi spoje jedou jaktakž dobře. Předtím jsem nikdy na žádném nebyl a ze všech Pyv to mám nejblíž.

Každopádně nedělá mi problém přijet na vejlet i na brněnské Pyvo. Nicméně soudě podle fotek na Twitteru, kolik lidí tam chodí, mám otázku, zda tam je vůbec někdě nějaký tišší koutek (líp mi vyvohuje klidnější atmoška), kde bychom to mohli všecko probrat.

**Comment by encukou** [comment]
Brněnské bude zítra, a je zrovna open-air; další nevím jak bude. Za mě Ostrava v pohodě, ale výsledky diskuse stejně musime někam sepsat.

**Comment by ghost** [comment]
Zítřejší bych nestíhal, tak to zatím necháme na to ostravské a pak se uvidí jak dál.

**Comment by honzajavorek** [comment]
A odkud teda jsi? :D

2016-08-24 17:54 GMT+02:00 Petr Viktorin notifications@github.com:

**Comment by ghost** [comment]
Relativně kousek od Ostravy.

**Comment by lspdv** [comment]
Neco malo informaci o tom jaky by mel byt profil juniora uz mame. Ale je to prazska verze

**Comment by ghost** [comment]
Super :+1: , aspoň něco od čeho se dá odpíchnout. Hlavně, ať je to ve finále co nejvíce konkretizované a plošné pro celou ČR. 

Přece jen, když se koukneme do inzerátů, tak `základy Pythonu`,  `základy Djanga / Flasku`, `základy databází` atd. jsou dost abstraktní pojmy a nikdo z nás zatím přesně neví, jaké minimální znalosti do toho spadají a které už jsou nad rámec požadavků.

**Comment by ghost** [comment]
Tak po dnešním ostravském Pyvu Vám snad @encukou poreferuje, co a jak jsme prodiskutovali ohledně akademie, respektive vzdělávacích materiálů.

**Comment by encukou** [comment]
@nait-aul, mohl bys sem dát fotku svých poznámek?

**Comment by ghost** [comment]
Pokud máš na mysli tu s Pythonem, tak:

![](http://image.prntscr.com/image/0d38ba0df4264b0ca8a1a9cce925add3.png)

P.S. Budu to ještě upravovat.

**Comment by encukou** [comment]
Měl jsem na mysli ty papírové, co jsi přinesl na sraz.

**Comment by ghost** [comment]
První stránka:

![](http://image.prntscr.com/image/28eb108012c445958a520a298411513e.jpg)

Druhá stránka: (nepovedla se)

![](http://image.prntscr.com/image/ff416bed05ef44dc85b5e1d3fa4e6327.jpg)

**Comment by encukou** [comment]
Nějaké poznámky – ne nutně všechno (co) se diskutovalo na Pyvu :)
- Aktuálně je následující krok je překlopit obsah z PyLadies na naucse. @Sanqui přitom chtěl učesat to HTML, ale vzhledem k tomu jak to jde rychle tam snad bude stačit jenom nahradit hlavičky/patičky.
- Obsah v několika formách je dobrý nápad. U každého příspěvku ale musí být jasné prerekvizity a co to člověka naučí.
- Témata bych nezaváděl, spíš seznamy toho, co pro naučení daného tématu potřebuješ projít.
- Padl nápad udělat "encyklopedii" – články ke konceptům ("seznam", "rekurze", "requests", "unit test", ...)
- Příklady k řešení s nezveřejněným řešením jsou problémové; bude to nejspíš potřebovat nějakou infrastrukturu aby to k něčemu bylo. Odložit.
- Znovu padl nápad nahodit stackoverflow/askbot
- Struktura a navigace se bude časem měnit; už teď se začátečnickým kurzem a odbočkama potřebujeme jinou než na čistý začátečnický kurz.

Jinak, jako vhodné formy mi přijdou:
- Tutoriál
- Workshop, formou poznámek pro kouče (jako doplněk k sepsanému tutoriálu)
- Tahák
- Projekty k řešení/domácí úkoly
- Referenční příručka
- Překlad specifikace :)

**Comment by frenzymadness** [comment]
Jen bych se rád ujistil, že správně chápu cíl projektu naucse.python.cz - tedy hlavně současnou fázi, kdy je třeba překlopit materiály. Je to tak, že v tuto chvíli by se měly vzít materiály z webu PyLadies, oprostit se od věcí, které se týkají kurzů samotných (odkazy pro organizátorky, data, oslovení, plánování ...) a zasadit to celé do hierarchické struktury odkazů tak, aby to i nově příchozímu dávalo smysl a dalo se tím projít od začátku do konce.

Je to tak?

Překlopit ten obsah zas tak složité asi nebude, protože jak psal @encukou tak na většině míst stačí jen upravit hlavičky/patičky, změnit odkazy a smazat nepotřebný obsah a soubory.

**Comment by ghost** [comment]
Ano.

**Comment by encukou** [comment]
Tak nějak:
- rozdělit obsah – věci jako organizační poznámky a úvodní prezentace ať zůstanou na pyladies.cz
- úprava – jak říkáš, hlavičky, patičky, odkazy
- na pyladies.cz dát redirecty na přesunutý obsah

Zasadit to do hierarchické struktury je druhý krok; mezitím se jako obsah dají používat i seznamy z pyladies.cz.

**Comment by encukou** [comment]
Vzdělávací materiály vznikají na naucse.python.cz;
hackhatony a workshopy pořádáme.

Školení pro firmy dělá Engeto. Myslím že by bylo rozumné s nimi spolupracovat,
co se firemních školení týče.

Co se rekvalifikačních kurzů týče, můžeme vytvořit materiály, ale
myslím že nemáme dostatečnou kapacitu dobrovolníků.

**Comment by encukou** [comment]
Pročetl jsem zdejší nápady, a přijde mi že každý buď:
* je na naucse (začátečnický kurz, některé workshopy),
* je plánovaný na naucse (jiné workshopy, příklady, standardizace), 
* je plánovaný jinde ([videokurz](https://github.com/pyvec/zapojse/issues/18), [firemní kurzy](https://github.com/pyvec/zapojse/issues/9)) nebo
* je velice časově náročný (rekvalifikační kurzy).

To na čem se úplně neshodneme, je důraz téhle issue na pracovní inzeráty a zaměstnatelnost. To pro mě osobně není zas tak velká priorita, a tudíž to potřebuje člověka, který by se tomu věnoval – ať už v rámci naucse (kde někoho s tímto zaměřením uvítám a rád pomůžu) nebo jinde v komunitě.
Nicméně si myslím, že k takovému člověku nám tahle issue nejspíš nepomůže, a autor issue si to na sebe  pravděpodobně nevezme :)

Tuto „vykopávací“ issue proto zavírám. Zájemce o spolupráci směřuji na https://github.com/pyvec/naucse.python.cz – a snílky na http://nauc.se/
