### ISSUE TITLE
Stanek, kde by byla mozna propagace Zapojse, naucse, PyLadies

### ISSUE THREAD

**Issue by lspdv** [pyvec/zapojse#41]
@hroncok navrhoval na Sprintu ve Msenem moznost stanku pro Pyvec na - tusim LinuxDays? 
Bohuzel jsem se s nim o tom jiz nestihla bavit. 

Bylo by mozne, aby na stanku byly i PyLadies, Zapojse a Naucse pokud to Pyvec vubec chce?
Mohla bych byt pritomna.

**Comment by hroncok** [comment]
Ano, LinuxDays.

Tohle všechno tam chceme.

**Comment by lspdv** [comment]
Skvele. Zjistim od kluku vic a ozvu se.

**Comment by honzajavorek** [comment]
Ja jsem mu uz na sprintu rikal nakej napad, ale uz nevim co to bylo. Jo!
Vim! Bylo to, ze Python u nas je hlavne o komunite a kulture, tak bychom
tam meli mit nakej ten Python folklor proste. Nejaky sestrihany video z
nasich akci, klidne stanek vytapetovanej fotkama z Pyv / PyLadies / atd.,
do toho z repraku nakej @vlinhart na uke :D :D ale jako myslim to celkem
vazne - proste ukazat, ze je to o lidech, a ze chces byt tohodle soucasti.

**Comment by honzajavorek** [comment]
Plus idealne aspon letacek s obsahem co bude zhruba na pyvec.org webu -
tzn. zapoj se, muzeme ti pomoct (pro lidi) a sponzoruj, dame tvym penezum
smysl (pro firmy).

2016-08-24 13:54 GMT+02:00 Honza Javorek mail@honzajavorek.cz:

**Comment by lspdv** [comment]
Skvely! Chtela bych s tim pomoci, ne jen za PyLadies. Je to dostatecne za
dlouho. Mohla bych si treba na starost vzit krome stani ve stanku a "byt
roztomila a zdvorila a povidat si s lidma" i nejakou tu pripravu. Myslim
si, ze tohle je hrozne super napad a pokud muzu udelat neco pro to, aby to
tam fakt bylo, tak jsem tomu ochotna venovat cas misto pyladies kurzu na
ktery chceme naverbovat byvale ucastnice a zase se vystridat.

Tohle bylo presne to, co jsem myslela tim, delat vic workshopu, akci -
propagace k tomu take patrila, jen me nenapadlo tohle. Ale je to presne to
s cim bych rada pomahala, aby muj zivot mel smysl :D :D :D hahaha..

Dne 24. srpna 2016 13:56 Honza Javorek notifications@github.com napsal(a):

**Comment by vlinhart** [comment]
Vam do stanku pujcim uke :-)

**Comment by lspdv** [comment]
je to uke i s tebou? ziva hudba to by byla pecka

2016-08-24 14:09 GMT+02:00 vlinhart notifications@github.com:

**Comment by vlinhart** [comment]
part time leda :-) 1/10 uvazek

**Comment by honzajavorek** [comment]
Zapomnel jsem, ze chcem @vlinhart v sokolskym kroji s uke, ale to je
detail. Verco bylo by super, kdyby ses toho nejak chopila :) Ale nenahazej
toho na sebe moc, at neskoncis jako ja :D

**Comment by hroncok** [comment]
Plus vám půjčím pyč.

**Comment by lspdv** [comment]
@honzajavorek, presne jsem cekala, kdy mi se Zuzkou tohle zase pripomenete :-) prave proto jsem psala o tom, ze organizaci pyladies bychom mely hodit zase dal na nejake jine holky a budu na to mit cas. 

Odesláno z iPadu
1. 8. 2016 v 16:13, Honza Javorek notifications@github.com:

> Zapomnel jsem, ze chcem @vlinhart v sokolskym kroji s uke, ale to je
> detail. Verco bylo by super, kdyby ses toho nejak chopila :) Ale nenahazej
> toho na sebe moc, at neskoncis jako ja :D
>

**Comment by kvbik** [comment]
ukulele banda (starena, dan, vladimir, eliska, veronicka a dalsi) by tam rozhodne mela byt (resp stridat se)

plus se nabizi treba fotrikuv lcd panel ci nejaka dalsi python hw instalace

**Comment by honzajavorek** [comment]
jooo ten LCD panel by mohl mit dobrej efekt

**Comment by lspdv** [comment]
Elinka dela Railsy

Odesláno z iPadu
1. 8. 2016 v 13:13, Jakub Vysoký notifications@github.com:

**Comment by kvbik** [comment]
re elinka> chodi na nase srazy taky, takze ji pocitam vic do nasi komunity! :))

**Comment by encukou** [comment]
Z LinuxDays se ozvali Pyvci, jestli nechceme stánek. Takže odpověď je ano? @lspdv, vezmeš si organizaci (delegování starostí na ostatní)?

**Comment by lspdv** [comment]
Jednoznacne ano! 

Odesláno z iPadu
1. 8. 2016 v 15:50, Petr Viktorin notifications@github.com:

**Comment by lspdv** [comment]
Zkusim popsat svuj navrh a zkusme to spolecnymi pripominkami upravit do lepsi podoby. Je to moje stankova premiera.

## Co chceme prezentovat?

**python.cz** 

> aby je navstevovalo vice pythonistu i zacatecniku zajemcu o python

> aby vedeli jake informace tam najdou

**pyvo.cz**

> protoze lide maji vedet, ze kazda zasadni zmena okolo mista ci casu srazu by se mela jako prvni objevit predevsim tam? tzn. naucit lidi hledat ze vsech kanalu dulezito info prave tady

**PyLadies a Advanced srazy**

> zvysit povedomi o PyLadies celkove (stale se setkavam jako organizatorka s tim, ze spousty python lidi o teto aktivite lidi z komunity vubec nevi)

> zvysit povedomi i u mensich firem, ktere by to jakkoliv rady podporily

> moznost jak zapojit zase nove kouce, kteri by napriklad opravdu radi Python ucili o moznosti na PyLadies nevi

**naucse.python.cz**

> otazka na @encukou  zdali jsme schopni za mesic posunou tuto novou vec tak, abychom ji tam mohli prezentovat?

> vidim to jako velmi zajimave doplneni stanku vedle PyLadies - bude pekne videt, ze mame zajem ucit vsechny bez rozdilu

**Zapojse a 📚  blog.python.cz**

> to by tam nemelo chybet

___

**Comment by lspdv** [comment]
@encukou @honzajavorek udelala jsem PR #44  na stanek soubor - prislo mi to lepsi nez to davat sem do vlakna, protoze snad uvidim kdo co komentoval
Stale je dost casu veci udelat relativne v klidu a vklidu = v pripade tisku i levne - pokud byste si nasli behem nasledujicich dnu par minut a okomentovali to, pomohlo by mi to. Diky a nemate zac! 😄

**Comment by frenzymadness** [comment]
Okomentováno, snad dobře a tak jak to bylo zamýšleno.
