### ISSUE TITLE
Shromažďování nabídek od sponzorů

### ISSUE THREAD

**Issue by zuzejk** [pyvec/zapojse#42]
Vypozorovala jsem, že hodně z nás má povědomí o nějaké nabídce od konkrétních firem/lidí na sponzoring, partnerství nebo další možnosti partnerství. Ale není to nikde přehledně sepsáno a někdo si to třeba poslechne a tu informaci nepředá dál, protože na to zapomene nebo se to prostě nedostane k  člověku na druhé straně republiky, kterého by to mohlo zajímat. Dá se s tím něco dělat? Nějaké shromaždiště takových formulovaných nabídek? Ať už pro pyladies, pyvec, djangogirls nebo cokoliv jiného... 
nebo je to blbost?

**Comment by lspdv** [comment]
To je skvely napad, jen by me zajimalo jak by sis to predstavovala. Jako verejny seznam? To nevim jestli je dobry napad a obavam se ze pyvec zrejme nema placenou soukromou cast githubu.

**Comment by zuzejk** [comment]
taky bych to neviděla na veřejně přístupné místo. právě i proto jsem to nadhodila, jestli by někoho něco vhodného napadlo. já jsem schopná vymyslet tak maximálně google tabulku přístupnou pouze pro zvané...

**Comment by kvbik** [comment]
soukroma google tabulka mi pro tenhle pripad prijde idealni.

**Comment by lspdv** [comment]
ale kdyz to chcem servirovat jako nabidky slecnam, bylo by fajn, kdyby to
melo lepsi vzhled nez jako google tabulka.
Krome toho, ze bych si to mohla sama naprogramovat - nezname nekdo nejakou
sluzbu, ktera by vypadala jako nastenka, byla verejna jen tomu, kdo ma
odkaz a mohly se tam jednoduse pridavat nabidky? Vylozene, kdyby to
vypadalo jako nastenka s listeckama a pripinackama, bylo by to Bozi! haha

2016-08-29 16:51 GMT+02:00 Jakub Vysoký notifications@github.com:

**Comment by zuzejk** [comment]
teďka nevim, jestli se správně chápeme... Takže já tedy původně myslela, že by to sloužilo vyloženě jen pro nás - hlavní organizátory jednotlivých eventů, v tuto chvíli hlavně Pyv, kurzů a jednorázových workshopů + asi někdo obecně za pyvec. Nevím tedy, o jakých slečnách teď píšeš, Verouši. Můžeš to upřesnit? :)

**Comment by lspdv** [comment]
aha :) nechapeme. ja myslela ze to chces pouzit uz jako nabidky na pyladies
kurzech a srazech,

v tom pripade souhlasim s @kvbik

Dne 29. srpna 2016 19:21 zuzejk notifications@github.com napsal(a):

**Comment by honzajavorek** [comment]
Takze udelame tabulku pod Pyvec organizaci na Google Docs? @zuzejk vzala by sis na starosti aby o ni mel kazdy povedomi a tak nejak ji opecovavala, aby nezvlčela?

**Comment by lspdv** [comment]
skvele, jen aby nam to nejak nekdo nemazal zvenku. navrhuji nedelat
tentokrat pristup tomu kdo ma odkaz ale udelat to na emaily.

2016-09-01 15:03 GMT+02:00 Honza Javorek notifications@github.com:

**Comment by zuzejk** [comment]
tak prozatím jsme to vyřešily pro pyladies google docs sharovanou tabulkou. je to přístupné i lidem s přístupem do materiálů pyvce, ale zatím nikdo další neprojevil touhu o tuto tabulku, tak to asi teď můžu uzavřít. uvidíme jak to bude fungovat.
