### ISSUE TITLE
Maluvky na samolepky

### ISSUE THREAD

**Issue by lspdv** [pyvec/zapojse#45]
Na samolepky python.cz nebo treba pyvo.cz

Samolepky budou kulate, tak asi nic roztahanyho nekresli. Klidne udelej oboji, muzeme tisknout ruzny verze za stejnou cenu a to cca 5Kc/ 24 ks

**Comment by honzajavorek** [comment]
![chodimnapyvo-text-rukou](https://cloud.githubusercontent.com/assets/283441/18616146/edb29a58-7db6-11e6-8c23-676e8ae8571a.png)
![chodimnapyvo-text](https://cloud.githubusercontent.com/assets/283441/18616147/ede110fe-7db6-11e6-95f8-8449a061eb49.png)
![hadi-text](https://cloud.githubusercontent.com/assets/283441/18616160/ef4e6c16-7db6-11e6-84cc-a2874aa0ba5c.png)
![hadi](https://cloud.githubusercontent.com/assets/283441/18616148/ee04add4-7db6-11e6-8788-f9af7e8c542e.png)
![laptop-text](https://cloud.githubusercontent.com/assets/283441/18616149/ee27394e-7db6-11e6-870d-049d061b4843.png)
![laptop](https://cloud.githubusercontent.com/assets/283441/18616151/ee3dbe80-7db6-11e6-8f53-503289904a9d.png)
![pyconcz-text-rukou](https://cloud.githubusercontent.com/assets/283441/18616156/ef06db12-7db6-11e6-980c-c6841b50149c.png)
![pyconcz-text](https://cloud.githubusercontent.com/assets/283441/18616150/ee2f6c9a-7db6-11e6-9ceb-65ec7562d5a7.png)
![pyconcz](https://cloud.githubusercontent.com/assets/283441/18616152/ee648b32-7db6-11e6-8a85-ca2b1441d50e.png)
![pylady-text-rukou](https://cloud.githubusercontent.com/assets/283441/18616158/ef3e7e14-7db6-11e6-879d-5e050b92d522.png)
![pylady-text](https://cloud.githubusercontent.com/assets/283441/18616159/ef44fee2-7db6-11e6-9ffe-7fd13724a550.png)
![pylady](https://cloud.githubusercontent.com/assets/283441/18616153/ee6fb6ec-7db6-11e6-9e74-cc5e22da7bf1.png)
![staff-text](https://cloud.githubusercontent.com/assets/283441/18616154/ee91ccb4-7db6-11e6-977a-ccdae3b1ee8f.png)
![staff](https://cloud.githubusercontent.com/assets/283441/18616155/ee9c11b0-7db6-11e6-9761-19db7dfa25d4.png)
![ukulele-text](https://cloud.githubusercontent.com/assets/283441/18616157/ef19c81c-7db6-11e6-8d8f-4464d43d9490.png)
![ukulele](https://cloud.githubusercontent.com/assets/283441/18616161/f019cc3a-7db6-11e6-9dc7-be5c90be2dd4.png)
