### ISSUE TITLE
Odkaz na podprojekt v zozname uloh 'zapoj se' ma rozbite url

### ISSUE THREAD

**Issue by apophys** [pyvec/zapojse#47]
Meno pull requestu vedie na pull request, modra ikonka s nazvom repozitara vedie na 404, nakolko je meno repozitara prehodene s menom organizacie

T.j. modra ikonka `python.cz` odkazuje na `https://github.com/python.cz/pyvec`

**Comment by honzajavorek** [comment]
Diky! Uz je na to Pull Request, opravujem opravujem!
