### ISSUE TITLE
hezci 404 na python.cz

### ISSUE THREAD

**Issue by starenka** [pyvec/zapojse#48]

**Comment by honzajavorek** [comment]
na to bych moh neco nakreslit

**Comment by starenka** [comment]
shrodigerova krajta ftw!

**Comment by mnovackova** [comment]
Mohlo by být něco takovéto?

![python-blush](https://cloud.githubusercontent.com/assets/18664225/24003035/96b31668-0a62-11e7-8ca9-907755a39916.png)

![python2](https://cloud.githubusercontent.com/assets/18664225/24003056/ad1453d6-0a62-11e7-91a0-330134334370.png)

![pyvo1](https://cloud.githubusercontent.com/assets/18664225/24003061/b219bf56-0a62-11e7-899e-2c8381b5d54b.png)


![pyvo2](https://cloud.githubusercontent.com/assets/18664225/24003085/cb220e5e-0a62-11e7-923a-208550965057.png)

**Comment by encukou** [comment]
Opraveno v https://github.com/pyvec/python.cz/pull/197 :)
