### ISSUE TITLE
Česká dokumentace ke Coconut

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#49]
[Coconut](http://coconut-lang.org/) je jazyk, který vychází z Pythonu a doplňuje lepší podporu pro funkcionální programování. Jaroslav Kubias (autor překladů [Učíme se programovat v jazyce Python 3](http://howto.py.cz/index.htm) nebo [Tkinter Pythonu 3](http://tkinter.py.cz/python_tkinter.html)) navrhl, že by překlad ke Coconutu zpracoval.

Napadlo mě, že by se to dalo publikovat třeba na [ReadTheDocs](http://readthedocs.org/), podobně jako ["Pyvec Guide"](http://pyvec-guide.readthedocs.io/), ale nejdřív jsem chtěl ověřit zájem. Chtěli byste překlad k jazyku Coconut?

Co na to takoví @hanpari nebo @horejsek, kteří zde diskutovali https://github.com/pyvec/zapojse/issues/38?

**Comment by horejsek** [comment]
Coconut mne nějak minul. Díky za upozornění. :-)

Co se mne týče, překlad nepotřebuji. Podívám se rovnou na jejich dokumentaci. Popravdě bych to udělal i kdyby česká verze už byla. Překlad je fajn, ale pokud se neupravuje s oficiální dokumentací a kódem, brzy je překlad zastaralý a velice pravděpodobně zbytečný. Kdybych překlad sám dělal, raději bych se spojil s autory a udělal překlad přímo do jejich dokumentace.

**Comment by Tovim** [comment]
Ahoj všichni,
jak jsem viděl v tematu #38, o funkcionální projektování v Pythonu by zájem mohl být. 
Autorem programovacího jazyka Coconut, který je nadstavbou jazyka Python, je Evan Hubinger, student Harvey Mudd College v Kalifornii. Jeho dokumentace je publikována na Read the Docs.
Požádal jsem jej o souhlas s mým překládáním. Pokud nebude proti, zeptám se ho, jestli by neuvažoval o
něčem podobným, jako je crowding.com/project/django-girls-tutorial. Jinak uvítám nabídku od Honzy 
Javorka publikovat překlad na github.com/pyvec, potažmo propojeném s "coconut.readthedocs.io".
PF 2017

**Comment by honzajavorek** [comment]
Prima, díky! Dej vědět, co ti odepíše a pokud by byl potřeba repozitář na Pyvec GitHubu, dej vědět :-)

**Comment by Tovim** [comment]
Hi all, Evan Hubinger souhlasí s mým překládáním a nabízí co navrhoval přítel Horejsek, to jest, že připojí můj překlad ke své dokumentaci.
Zdař Bůh

**Comment by honzajavorek** [comment]
@Tovim 👍 dáš sem pak do komentáře odkaz, až to bude, prosím?

**Comment by Tovim** [comment]
Ano, dám.

**Comment by Tovim** [comment]
S potěšením  oznamuji, že zájemci o Coconut si mohou číst českou dokumentaci na adrese http://coconut-lang.org, poté co se proklikají přes Tutorial či Documentation k české verzi. Bohužel nám ještě nechodí dobře hooky, takže uvedená adresa prezentuje překlad předposlední verze dokumentace.
Poslední verzi lze vidět na mém prozatimním sajtu http://potomek.readthedocs.io/cs/latest/.
Ještě napsat ten zamýšlený oslí můstek k funkcionálnímu programování coby přílohu B v howto.py.cz a je to hotový.
Tovim

**Comment by Tovim** [comment]
Addendum:
Hook již chodí. Coconut je tedy přístupný přes klikání na http://coconut-lang.org nebo přímo na http://coconut.readthedocs.io/cs/master/.
Tovim

**Comment by Tovim** [comment]
Netýká se Pythonu, proto do dávám do samostatného kotce:
Kdo se zajímá o programovací jazyk Red, může si číst jeho dokumentaci česky na https://doc.red-lang.org/cs/. Jazyk je ve fázi 0.6.2 a jeho dokumentace se vyvíjí.
O české komunitě kolem Redu nevím.
Tovim

**Comment by honzajavorek** [comment]
Prima, takže hotovo! 🎉
