### ISSUE TITLE
Vytvořit příručku pro organizátory srazů

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#5]
Záblesky chtění zde: https://github.com/pyvec/guide
### Smysl
- aby ti, kdo přijdou po nás, nedělali naše chyby
- aby ti, kdo chtějí založit sraz ve svém městě, aby to měli snazší
### Může pomoci

Existují nepříliš používané Trello boardy jednotlivých Pyv, ze kterých jde leccos vyčíst:
- https://trello.com/b/xiajIREV/brno-rutina-ka-deho-srazu
- https://trello.com/b/Mi3dSO22/ostrava-rutina-ka-deho-srazu
- https://trello.com/b/60aClntd/prazska-pyva

Stavět se dá (by se mělo) i na https://wiki.python.org/moin/StartingYourUsersGroup, ale je dobré to brát v českém kontextu.
### Nápad: propagace franšízování

Nápad @honzajavorek - nikým neschválený a neprojednaný:

> V souvislosti s příručkou mě napadlo - pro koho by byla? Pro naše nástupce (validní)? Pro další organizátory? Jsou u nás ještě další města, kde by se mohlo Pyvo chytnout? Podle mě asi moc ne. Ostrava bojuje s návštěvností, a to se už taky spojuje s Rubysty. Python je pro malé město moc úzké vymezení. Příkladem budiž http://tkalci.cz/ ve ValMezu - jen s Pythonem by měli asi problém, ale tím, že je sraz obecnější, tak tam lidi chodí. Napadlo mě tedy - nemohli bychom do budoucna Pyvo "franšízovat"? Tzn. říct, že když sraz v nějakém městě prohlásí, že je "krom jiného i Pyvo" a bude tuhle značku propagovat, budeme my propagovat jej a poskytneme mu zázemí. Je to vlastně možné už teď, ale byl by to psychologický rozdíl. Na python.cz by pak mohl být malý návod "chceš mít Pyvo ve svém městě?", kde by byly instrukce, co pro to mohou udělat (jak třeba existující sraz krom jiného obrandovat i jako Pyvo).
### Co je potřeba udělat

Napsat ji :-)

---

@msgre Ahoj. Přečetl jsem si sekci "Příručka pro pořadatele srazů" a mám k ní pár připomínek:
-    **Jak můžu své srazy propagovat prostřednictvím Pyva?** Na stránkách pyvo.cz jsou srazy pro Prahu, Brno a Ostravu. Letmo jsem prohlídnul zdrojáky a vypadá to, že srazy generuje z databáze. Je někde vystaveno rozhraní pro jejich zadávání?
-    **Pravidelnost srazů** Narozdíl od vás si myslím, že pravidelnost srazů je důležitá. Ideálně co měsíc, ale když to nejde, tak klidně i s větší periodou. Náhodné srazy podle mě mají tendenci vyhnívat (není tam žádný závazek kterého bych se držel)
-    **Vydrž!** Je normální, že energie a touha potkávat se s lidma a podílet se na organizaci srazů časem vyprchává. Mě vydržela asi 2 roky. Je fajn, pokud se do té doby utvoří silné jádro, které spolupracuje.
-    **Není každý den posvícení** Myslím že učitelé to mívají podobně -- úspěch srazu (vyučovací hodiny) nekoreluje s úsilím, které se do něj vloží. Mockrát se mi stalo, že pečlivě připravá schůzka zas tak dobře nedopadla, a naopak předem odepsaný sraz (třeba kvůli odřeknutým výstupům na poslední chvíli) byl boží. Hodně to souvisí i se složením lidí kteří dorazí (může se stát že vlivem počasí/nemocí nedorazí nikdo). Zkrátka, je třeba se předem obrnit a v případě neúspěchu nehledat hlavní příčinuv sobě.
-    Do sekce **Vhodné místo konání**, seznamu věcí, bych přidal explicitně prodlužky (ikdyž jsou zmíněné někde kousek níž)
-    K dokumentování srazů na **Lanyrdu** či jinde -- osobně to vnímám jako službu, poděkování vystupujícím (pokud samozřejmě explicitně neřeknou, že záznam nechtějí). Z osobní zkušenosti vím, že pokud se např. ucházím o novou práci, můžu svou aktivitu doložit nejen realizovanými projektu, GitHubem, ale právě i výstupy na akcích podobným Pyvu.

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/xPOQjBDg/8-vytvorit-prirucku-pro-organizatory-srazu).

**Comment by honzajavorek** [comment]
Pozn.: Až to bude, dám to přečíst @TomasVotruba, ať mi to zkritizuje. Ještě nějaké poznámky z mého osobního tudů:

> az to bude, dat na review vsem co delaji srazy, vcetne tkalcu a sk nahazet tweety s obsahem z meetup guide na napyvo channel
> Chcete založit Pyvo ve svém městě?
> Franšíza: Chcete váš sraz na jeden den proměnit v Pyvo?
> původ názvu pyvo, slovensko
> kalendar kdo zrovna organizuje, ownership

**Comment by kvbik** [comment]
neco uz psal @whiskybar nebo mel rozepsane. ale ted ma deti, tak mozna ani on nevi, kde to ma :D :D

**Comment by whiskybar** [comment]
Psal jsem to ale anglicky, klidne z toho cerpejte (do cestiny), no rad bych, aby tam vetsina bodu zaznela, protoze jsou to poznatky z terenu; vetsinou od lidi, kteri se nas ptali.

https://gist.github.com/whiskybar/f601770a40b54ea5b9d1c7188ef208db

**Comment by honzajavorek** [comment]
Super!!! mrknu na to

**Comment by honzajavorek** [comment]
Poznámka: až to bude, mělo by se na pyvo.cz přidat

- jasný návod jak přidat informace o srazu do databáze
- jak přidat informace o srazu v jiném městě než p-b-o (viz dotaz od @msgre výše)
- odkaz na příručku jak založit sraz ve svém městě
- dát jasně najevo jak se sraz může přidat do https://github.com/pyvec/python.cz/issues/220

**Comment by encukou** [comment]
Toto je na https://pyvec-guide.readthedocs.io/guides/meetup.html .
Jsou tam začleněné všechny návrhy odsud?

**Comment by honzajavorek** [comment]
Vytvořená asi nějak je, hotová není. Založil jsem issues v odpovídajícím repozitáři.
