### ISSUE TITLE
Videozáznam všech python přednášek

### ISSUE THREAD

**Issue by taryodor** [pyvec/zapojse#50]
Postupně se zvyšuje množství různých kurzů a workshopů a není v silách jednotlivce vše navštěvovat. Napadlo Vás, že by se vše dokumentovalo pomocí nějakého chytrého softwaru?
Kupříkladu toto?
https://slideslive.com/
Bylo by úžasné moci si projít neopakovatelné výstupy Python-Mastera V. Ch. vykouzlené náhodným dotazem z davu. 
Tyhle improvizací okořeněné osobní přednášky vydají za 317 psaných materiálů...

**Comment by encukou** [comment]
Pyva se natáčejí, jen ta videa nemám čas zpracovávat. Rád zaučím, jen to holt potřebuje čas.

SlidesLive mi přijde pro neziskovku příliš drahé.

**Comment by encukou** [comment]
Co se kurzů týče, můžu odpovědět jen za sebe v Brně. Odpovídám se zpožděním, protože jsem chtěl předtím, než napíšu svůj názor, dát prostor ostatním... ale to se moc nepovedlo.

Začátečnické kurzy nenahrávám. Jde tam hodně o komunikaci s publikem, kterému nemusí být příjemné že ho někdo zaznamenává. Rozhodně takhle nechci přijít o dobré otázky od už tak dost nesmělých lidí.

Pokročilý (ale nenavazující) kurz, MI-PYT nanečisto, jsem nahrával (stejná situace jako u Pyva). Bylo to koncipované hlavně jako přednáška, ale stejně to nakonec bylo dost na míru publiku, takže nemyslím že by to bylo užitečné ostatním. Takže to ani neplánuju zveřejnit – na rozdíl od psaných materiálů, které píšu přímo proto, aby je mohl použít kdokoli (což není samozřejmé, a trvá to tak cca 2-4× déle než připravit přednášku se stejným obsahem).

Workshopy – ty mají výhodu je v tom, že ti tam lidi poradí s konkrétním problémem, který právě máš. Jinak by to mohla být neinteraktivní přednáška (viz Pyvo), která se na natáčení hodí mnohem víc.

Co se neopakovatelných výstupů týče, myslím že jsou často opravdu neopakovatelné a na záznamu ztrácí své kouzlo. (Teda pokud se na to dívá někdo, co tam naživo nebyl...)
A tak budu podporovat spíš předpřipravená videa (#18).

**Comment by encukou** [comment]
Každopádně tohle jsou všechno důvody proč má *u mě* prioritu Pyvo spíš než kurzy/workshopy.

**Comment by taryodor** [comment]
Děuji za vyčerpávající odpověď.
Rozumím, jsem zticha.

**Comment by honzajavorek** [comment]
Já bych to viděl podobně. Už na Pyvu jsou lidi někdy nervózní, když se přednáška natáčí a nechovají se přirozeně. U výukových přednášek by to byl ještě větší problém. Pokud výuka přes video, tak mi přijde #18 jako lepší řešení téhož problému.

> Bylo by úžasné moci si projít neopakovatelné výstupy Python-Mastera V. Ch. vykouzlené náhodným dotazem z davu.

To souhlasím, ale problém je právě v tom, že kdyby se to natáčelo, ten dotaz by nejspíš ani nepadl.

**Comment by encukou** [comment]
Nebyl účel tě utišit, jen jsem řekl proč to nedělám.

Každopádně děkujeme za připomínku, i když nevyšla!

**Comment by taryodor** [comment]
Jé, já to tak nemyslel. Zámysl mého sdělení bylo říci, že k tomu já nemám co říct, protože jsi mi odpověděl doopravdy vyčerpávajícím způsobem :-)

**Comment by encukou** [comment]
OK, jsem rád že z toho není nedorozumění.
