### ISSUE TITLE
PyWorking web

### ISSUE THREAD

**Issue by messa** [pyvec/zapojse#60]
Ahoj, napadlo mě, že by Pyworking měl mít nějakou digitální stopu.
Zkusil bych udělat nějaký jednoduchý web s popisem a přehledem workshopů.

Máte k tomu nějaké nápady? Zuzana V. navrhla, že by se to mohlo propojit s NePyvo srazy, mě přijde, že je to dost jiná věc. Ale klidně se můžeme zamyslet, jak pomoct s prezentací všeho co není Pyvo.

**Comment by messa** [comment]
Teď koukám, že NePyvo už na Pyvo.cz je, ale odnikud se k tomu nedá doklikat: https://pyvo.cz/nepyvo/ Pro jistotu se to ani nedá vygooglit. https://github.com/pyvec/pyvo-data/pull/12

**Comment by encukou** [comment]
"jak pomoct s prezentací" -- ideálně to přidat na homepage pyvo.cz. Mám to (pro NePyvo) v TODO, ale příliš nízko :(

**Comment by kvbik** [comment]
I pyworking vy bylo fajn mit ba pyvo.cz jsou tam i pycony a tak.

**Comment by encukou** [comment]
Přidáme na sprintu? :)

**Comment by messa** [comment]
Kde jsou pycony na pyvo.cz? Pycony jsou přeci na pycon.org. Ani videa na pyvo.cz mi přijdou, že tam není žádné z PyConů.

Dávalo by mi smysl různé akce (tj. to co @kvbik navrhuje dát na pyvo.cz) mít na python.cz a na pyvo.cz jen Pyvo. Pyworking není Pyvo, organizátoři Pyva nejsou organizátory Pyworkingů, to samé pro Nepyvo a pro Pycon.

**Comment by messa** [comment]
Jestli ale bylo myšleno dát na pyvo.cz odkaz tak jsem samozřejmě pro, předchozí komentář jsem psal v duchu kde mají ty věci "bydlet" :) případně kde agregovat vyloženě seznamy meetupů.

**Comment by honzajavorek** [comment]
Takhle - dřív byly jen Pyva. Pak byly PyLadies, ale ty mají vlastní web. Pak byly PyCony, ale ty mají vlastní web. A teď je spousta dalších akcí, pravidelných i jednorázových, které vlastní web nemají, a vlastně by asi ale bylo zbytečný, aby měly, když by šlo v zásadě o podobný styl webu jako je pyvo.cz. Takže je idea připlácávat to zatím do pyvo.cz a vylepšovat postupně pyvo.cz, aby na něm mohly být všechny akce (proto taky už není `https://pyvo.cz/praha/`, ale `https://pyvo.cz/praha-pyvo/`, i když to svým způsobem vypadá divně).

Samozřejmě by časem asi dávalo smysl to nakonec spojit dohromady a mít to všechno na python.cz a nechat pyvo.cz přesměrovávat tam. Ale jde i o to, kdo vlastní jakou doménu apod. 😉 Časem to klidně spojme pod jedno, ale zatím bych se snažil aspoň vylepšovat to pyvo.cz a přidávat nové akce do něj.

Vlastně bychom měli na https://github.com/pyvec/pyvo.cz/issues otevřít issue "ať je pohodlné přidávat i jiné akce než Pyvo".

**Comment by honzajavorek** [comment]
(Jinak teda Zuzana V. je @zuzejk)

**Comment by zuzejk** [comment]
Nevím, jak nePyvo, ale PyWorking svým charakterem rozhodně pod Pyvo ani náznakem nepatří a nevidím proto v propojení s Pyvem vůbec žádný smysl.

**Comment by zuzejk** [comment]
mně se spojení PyWorkingu s Pyvem nezamlouvá, asi nejen kvůli tomu že to asociuje chlastací akci

**Comment by honzajavorek** [comment]
Domluvili jsme se, že PyWorking bude mít vlastní web. Propojení s ostatními aktivitami proběhne přes https://github.com/pyvec/python.cz/issues/220. Web si berou na starost @messa a @zoellenka. Vytvořili jsme repozitáře a tým @pyvec/pyworking.

**Comment by honzajavorek** [comment]
Domluvili jsme se, že PyWorking bude mít vlastní web. Propojení s ostatními aktivitami proběhne přes https://github.com/pyvec/python.cz/issues/220. Web si berou na starost @messa a @zoellenka. Vytvořili jsme repozitáře a tým @pyvec/pyworking.

**Comment by messa** [comment]
**Web pro Pyworking je vytvořený: [pyworking.cz](https://pyworking.cz/)**

Github repo (i pro případná issues): https://github.com/pyvec/pyworking.cz
Počítám s tím, že tam bude ten ical export: https://github.com/pyvec/pyworking.cz/issues/1

**Comment by honzajavorek** [comment]
Tak tím pádem zavíráme ✨ 👍
