### ISSUE TITLE
Pyvo v Olomouci

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/zapojse#61]
Už máme dva aktivní členy komunity v Olomouci a to jak známo bohatě stačí k přidání Olomouce na mapku Pyv v ČR.

Otevírám tedy toto issue pro @fivaldi a @mcurlej a můžeme se do toho pustit. Pomohu jak jen to půjde a jistě nebudu sám. Přinejmenším zajistíme obsah na první pyvo.

Zbývá vybrat prostory, zvolit datum, sehnat někde projektor (stačí zapůjčit), vybrat téma a začít s propgací. Nějaké nápady? :smile:

**Comment by honzajavorek** [comment]
Něco mi říká, že z Olomouce je i @JanBednarik.

**Comment by kvbik** [comment]
I Pražáci se chtějí do Olomouce podívat! Ano! ;)

**Comment by JanBednarik** [comment]
Hlásím se jako Olomoučák :-)

**Comment by fivaldi** [comment]
Okeeej, takže v tuto chvíli v ideálním počtu máme 3 místní a pár přespolních..

Čili potřebujeme:
- vybrat místo (ideálně s dataprojektorem)
- sehnat/zapůjčit daťák, pokud nebude přítomen v místě
- zvolit vhodné datum
- vybrat téma
- vypropagovat to mezi lidi/firmy, na sociální sítě etc.

**Comment by frenzymadness** [comment]
Pokud by mělo dojít na pravidelné pořádání, tak doporučuji zvolit druhý týden v měsíci, protože mezi prvním (Ostrava) a třetím (Praha) je vždy jeden volný, ale mezi Prahou a Brnem tomu tak vždy není a tak by se to mohlo krýt. Den v týdnu je na vás.

Téma by mohlo být něco jako "Nulté pyvo" kde bychom přišli a představili příchozím celý koncept a historii Pyva atd. a pak od dalšího už by se mohlo začít s čímkoli dalším.

**Comment by MarrekNozka** [comment]
Ahoj. Hlásím se taky jako Olomoučák. Mám jen jeden malý problém. Můj zájem o Python a láska k němu naráží na nelásku k hospodám. Proto se prám, musí se na tom místě, co se ještě pořád hledá, točit pivo? Nebo stačí, že je tam hezky, teplo, projektor, případně čaj a sušenky? 

Pracuju na [VOŠ a SPŠE Olomouc](http://www.spseol.cz/), takže pokud by byl zájem, projektorů, počítačů, učeben a podobných věcí je u nás poměrně dost. Nevím, jestli je zrovna naše škola tím nejlepším místem pro Pyvo, ale pokud by byl zájem, domluvit by to myslím nějak šlo.

**Comment by frenzymadness** [comment]
@tlapicka Zvykem je, že je na místě k dispozici nějaké jídlo a pití a proto to je většinou někde v restauraci/hospůdce. Nehledě na to, že je to většinou v době večeře a nemálo lidí příjde přímo z práce. V restauracích je často k dispozici nějaký salónek nebo tak něco, takže by to asi ani nemusel být problém. V té ostrávské máme například něco jako vinárnu.

Nicméně je samozřejmě možné to chytit za druhý konec a udělat to někde mimo a jídlo a pití zajistit třeba objednávkou z nějaké pizzerie nebo tak. Fantazii se rozhodně meze nekladou.

**Comment by MarrekNozka** [comment]
@frenzymadness Jo chápu. Vím, že je to můj osobní problém.  :-)

**Comment by honzajavorek** [comment]
Tak otázka je, k čemu přesně máš nechuť. [Tkalci](http://tkalci.cz/) se schází v interiérově luxusní [Schlattauerově kavárně](https://www.facebook.com/schlattauerovakavarna). Kdo chce, dá si tam pivo, kdo nechce, dá si tam limču nebo čaj. Byl jsem tam a bylo to moc fajn. Možná máte v Olomouci podobný prostor? Cafe 87 bude asi malé, ale třeba jsou další.

**Comment by fivaldi** [comment]
Ahoj.

Těžko dopředu odhadnout velikost olomoucké komunity, takže navrhuji přidat se ze začátku k něčemu, co už tu již bylo. Namátkou jsem našel toto:
https://www.facebook.com/events/826449300827432/
Tato akce podle všeho měla již dva termíny:
http://srazy.info/olomoucke-it-pivo/7084
http://srazy.info/olomoucke-it-pivo/7332
Dokonce existuje důkaz v podobě fotografie 😃:
https://goo.gl/maps/iTi1zgosG812

Výhody:
- Pokud by se podařilo spojit s organizátory a oslovit skrz ně minulé účastníky, existuje naděje na hojnou a pravidelnou účast.
- Pokud by zde takto časem vznikla početná PyKomunita, mohla by se osamostatnit/vyčlenit.
- Pro zájemce z řad studentů je to "co by kamenem dohodil", viz: https://goo.gl/maps/GDimr7at1Jo
- A v neposlední řadě, ehm, ehm, to mám taky "co by kamenem dohodil a zbytek doběhl". 😃

**Comment by JanBednarik** [comment]
IT piva už jsou asi pasé. Ale v tomhle roce se začaly organizovat nějaké srazy ve FB skupině Webdev Olomouc: https://www.facebook.com/groups/1874049622825379/

**Comment by JanBednarik** [comment]
Tak koukám že to jsou jiná IT piva. Ony nějaké probíhaly před několika lety, ale to byly asi jiné.

**Comment by mcurlej** [comment]
Zdravim,

@fivaldi S pridanim sa k inym komunitam bude asi mansi problem, kedze asi tie budu tiez orientovane na nejaku technologiu. Ale vyskusat to mozeme aspon pre reklamu, ze sa mozme zucastnit nejakych stretnuti inych komunit. Obvolam ludi co poznam v Olomouci aby nam aspon urobili nejaku tu reklamu. Respektive ci vobec budu ochotny.

@tlapicka Myslim si ze len treba najst nejaku normalnu hospodu. Vsetky su uz teraz nefajciarske takze az taky problem by to nebol. Ja vsak zatial poznam iba tie standardne ako Drapal, Moric etc. (Ziadny salonik ani projektor. Pokial viem...) Takze pomoc v tejto oblasti by sa zisla.

Co sa tyka zoznamu co napisal @fivaldi myslim si, ze priestory a reklama budu asi tie najtazsie. Co sa tyka zvysku tak toto ma napadlo hned s fleku:

**Datum:** @frenzymadness napad s 2 tyzdnom v mesiaci je pre mna ok. Co sa tyka dna tak Stvrtok (informaticky piatok ;)) sa mi pozdava.
**Temata:** Na prve pivo je to celkom jednoduche. Uvod do Pythonu si berem ja. Myslim si, ze @frenzymadness nam ako veteran moze povedat nieco o Pyve v CR a tak (Predpokladam, ze takych talkov mas uz pripravenych aspon 5.). Takze dva by boli. Zvysok neviem. Ktokolvek sa ale moze pridat s napadom.. :)

Problem s tymito napadmi bude iba vtedy ak nikto nepride... :D Mysli novy ludia....

**Comment by fivaldi** [comment]
@mcurlej, souhlasím, že ideální to není, ale udržet častost konání a početnost návštěvníků Pyva v městě velikosti OL bude minimálně ze začátku challenge. Inspiraci jinými technologiemi může být i přínosem. Pyvo (aspoň ta, která jsem absolvoval) obsahuje kolikrát i přednášky na témata pouze okrajově související s Pythonem, ale jsou minimálně inspirativní a zajímavé.

Jinak s hospodami mám zatím referenci na Mořice (Drápal salonek nemá) a na Jízdárnu, která je však mimo centrum OL. Co se týká propagace, určitě pomůže anoncovat to na co nejvíce kanálech.

Prosím ještě o zvážení té varianty s Dogou. Ať už samostatně či v součinnosti s jinými organizátory jiných IT aktivit. Jde o to, že (geograficky) nejsnáze najdeme publikum. Horší bude samozřejmě sehnat přednášející.

**Comment by mcurlej** [comment]
@fivaldi Co sa tyka hospod tak Moric, je fajn. Potom poznam este Renome co je tiez v centre, ma salonek ale neviem ci ma projektor. Ohladom na komunity asi by sme mali ist na prieskum co vlastne v Olomouci je.

**Comment by frenzymadness** [comment]
Já bych to zcela upřímně s nikým jiným nespojoval, protože pak to nebude moci být pod stejnou značkou jako ve zbytku republiky a případné osamostatnění jen bude nutit účastníky k rozhodnutí, kde chtějí dále chodit. Reklama nebude problém, protože na první setkání to vyborbardujeme napříč celou komunitou a pak už se minimálně někteří z oslovených udrží. Pomoci by v tom mohly školy, firmy, ale třeba i jiné skupiny, jak napsal Martin. Navíc na meetup.com například bude pozvánka doručena všem z okolí, kdo podobné aktivity sledují. Také to samozřejmě nemusí být každý měsíc a ani to nemusí být na specifické téma.

Za mě:
* Udělal bych to na 100 % jako Pyvo, i když to ne vždy musí být nutně o Pythonu. V Ostravě se to taky povedlo a to tu moc firem zaměřených na Python není. Naopak nám pomáhají firmy jako Tieto nebo GMC, které jednou v úplně jiných technologiích.
* Pokusil bych se nalákat lidi z jiných aktivních i méně aktivních komunit (a těch méně aktivních bude určitě více, takže budou rádi za něco nového)
* Pro začátek bych si nestanovoval vysoké cíle a dělal Pyvo
    * nepravidelně, jak bude chuť, čas či dostatek přednášejících
    * nebo pravidelně, ale ne pokaždé s hvězdným obsazením a konkrétním obsahem, ale třeba jen diskusní Pyvo pro pár skalních, kteří alespoň vymyslí, co dál.

**Comment by honzajavorek** [comment]
Hlavně co mi přišlo jako velké ponaučení z Ostravy, tak pokud ve městě už není nějaká Python komunita, je dobrý mít obsah Pyva zaměřený na úplné začátečníky. Zní to samozřejmě, ale nám to na začátku nedošlo, bych řekl.

Ještě si tu odložím tohle: [Příručka pro pořadatele srazů](https://pyvec-guide.readthedocs.io/guides/meetup.html). Pokud si to někdo přečte a pak založí Olomouc, tak jsem to celé nepsal úplně zbytečně 😄

**Comment by frenzymadness** [comment]
Právě jsme měli rozhovor s @fivaldi a tak nějak jsme se dohodni na následujícím:
* První Pyvo by mohlo být ve čtvrtek 9. listopadu. Na organizaci jsou dva měsíce a je to ještě daleko od svátků. Dělat první Pyvo v prosinci nebo v lednu nám nepříjde úplně dobrý nápad nejek kvůli svátků, ale třeba také studentům.
* Program by mohl být následující:
    * O čem je Pyvo a co vlastně dělá Python komunita v ČR (Lumír)
    * Open source software a kolaborativní přístup k vývoji (Filip)
    * Úvod do Pythonu (Martin)
* Co je třeba udělat ještě před oznámením
    * Sehnat a zarezervovat prostory, abychom měli jasno ještě před propagací na soc sítích
* Propagace
    * Facebook event, meetup.com (placená služba), pyvo.cz, python.cz, twitter.com atp.
    * Odeslat mail firmám, školám s IT zaměřením, známým, do Red Hatu, na Slack atd. atd.
    * Pokusit se sehnat sponzora. To se dělá lépe po známostech a mohlo by to zvednout zájem o první Pyvo.
* A dál:
     * Sehnat projektor, pokud nebude na místě k dispozici

Klidně doplňte, co vás napadne.

**Comment by fivaldi** [comment]
Co se týká místa konání, kloním se k těmto kritériím:
- `import` **Vhodné místo konání** `from` **Příručka pro pořadatele srazů**
- V centru/blízko centra
- Snadná dostupnost od vlak. nádraží
- Blízko 17. listopadu 12 (katedra IT/UPOL)

**Comment by kvbik** [comment]
datum> proc az v listopadu, zarijovy i rijnovy druhy ctvrtek jsou jeste pred nami?:)))

projektor> na prvni olomoucove pyvo rad privezu. aspon budu mit o duvod vic prijet!

sponzori> o co by se jednalo? mensi castky neni potreba hned hledat firmu, ale da se resit pres pyvec.org - samozrejme je dobre lokalni vazby vyuzit a treba az pro pripadne pravni posveceni sponzoringu vyuzit pyvec transparentni ucet

**Comment by fivaldi** [comment]
> datum> proc az v listopadu, zarijovy i rijnovy druhy ctvrtek jsou jeste pred nami?:)))

Hlavně kvůli a) organizaci/organizátorům, b) propagaci, která bude potřebovat čas, a c) kvůli publiku: Studenti zde v září ještě nejsou a v říjnu budou mít mnoho úvodních starostí a svých vlastních akcí.

> projektor> na prvni olomoucove pyvo rad privezu. aspon budu mit o duvod vic prijet!

Uvidíme podle místa, ale hoooray \ó/ i kdyby byl jen do zálohy/rezervní, díky moc za nabídku/ochotu! :-)

**Comment by fivaldi** [comment]
Byl jsem zjišťovat možnosti v té "Doze", kterou jsem odkazoval výše, kde letos proběhly ty (rovněž odkazované) IT srazy.

Výhody/neutrální věci:
- Je to blízko PřF (katedra IT), tudíž tam chodí tam studentstvo.
- Tramvají/busem je to pár minut od nádraží, pak pěšky kolem řeky po chodníku/cyklostezce (max. 5 minut chůze).
- Dá se tam najíst (nevyzkoušeno), skladba lístku zněla slušně. U venkovního posezení se přes léto griluje a obstojně vaří (vyzkoušeno).
- Je tam salonek, kde se pohodlně vejde ~20 lidí.
- WiFi tam je, jen je třeba ji ověřit.
- Zabookovat je vhodné aspoň 1-1,5 měsíce dopředu.
- Bezbariérové.
- Letní posezení venku pro letní srazy.
- Pro ozvláštnění srazů (např. přes léto) možnost pohybových aktivit u řeky, jsou tam hřiště, dá se zorganizovat projížďka na Ololodi apod.
- Zásuvky 230V, osvětlení lze samostatně regulovat pro salonek.

Negativa/neznámé věci/obavy:
- Připomíná to nálevnu. :( Do salonku se musí projít až dozadu prostorem mezi stoly a kulečníkem.
- Chybí tam plátno a projektor, nutno dořešit.
- Nevím, jaký je tam ruch večer, jestli by to nerušilo i v salónku. Čtvrteční večery tam bude pravděpodobně - vzhledem k typickému studentskému životu - docela rušno.

**Comment by frenzymadness** [comment]
@fivaldi Já bych se toho nebál a přinejmenším to zkusil. Změnit se to v případě nespokojenosti dá vždy. Zkusil bych se domluvit s provozním, jestli neplánují nákup projektoru a plátna, že by jim to v salónku mohlo sloužit i pro další podobné akce a pokud ne, tak si to nějak splašíme sami.

Pokud si chcete být opravdu jistí, vezmi @mcurlej a další a skočte se tam některý večer čtvrtek/pátek podívat a uvidíte, jak špatné to s hlukem bude.

**Comment by fivaldi** [comment]
Zamluvil jsem místo v salonku v http://www.pivnicedoga.cz/ na termín 9.11. od 18:00 (zahájení bych dal ale až na 19:00?). Plátno by mělo být na místě k dispozici. Ještě zajdu ověřit jeho stav :-) a rovněž to připojení na internet.

Jestli máme už kompletní seznam přednášek (já @fivaldi, @frenzymadness, @mcurlej, příp. kdo další?), tak navrhuji začít s propagací, viz Lumčův seznam:
>    Facebook event, meetup.com (placená služba), pyvo.cz, python.cz, twitter.com atp.
>    Odeslat mail firmám, školám s IT zaměřením, známým, do Red Hatu, na Slack atd. atd.

**Comment by wotaen** [comment]
Čau všichni, vítám IT srazy v Olomouci. Napadlo mě, že alternativa hospody by mohlo jít třeba do coworkingu Honzy Linharta. 
Výhody - lednice na pivo, kafe, projektor, internet, whiteboard, klid, neomezený čas + možná šance přilákat více lidí
Nevýhody - není obsluha :), Honza taky pořádá srazy (kolize?), ale jsou asi pro jinou audience

Akorát teda budu rád, když bude příště jiné datum než čtvrtek...

**Comment by frenzymadness** [comment]
@wotaen Skvěle, díky! Pyvo v Praze, Brně i Ostravě je dost spjato s pivkem a večeří, takže my spíše preferujeme nějakou restauraci, ale Olomouc může mít samozřejmě zcela odlišný model a třeba se do budoucna coworking osvědčí daleko více. Uvidíme, co řeknou příchozí na nultém Pyvu.

@fivaldi Zkusím připravit vše potřebné na pyvo.cz a pošlu PR. Pak to můžeme protáhnout do nějaké skupiny na facebooku a začít s propagací, když už to bude online.

**Comment by mcurlej** [comment]
@wotaen Ahoj Michale, pozrel som sa na ich stranku. Otazka znie ci by to bolo free? Lebo vyzera to tak, ze je to cele na prenajom iba. Ale ako @frenzymadness pise skusime to v hospode zo zaciatku.

**Comment by wotaen** [comment]
@mcurlej Ahoj, free by to určitě nebylo (zase by bylo levnější pivo, takže by to asi vyšlo šul nul). Můj nápad byl ten, že to bude takové komorní setkání s basou piv a pizzou z dovozu :). Ale domluvené už to máte v hospodě, tak asi nemá cenu to dál řešit...aspoň pro teď.

**Comment by fivaldi** [comment]
Související: https://github.com/pyvec/pyvo-data/pull/38

**Comment by frenzymadness** [comment]
A další související je toto https://github.com/pyvec/pyvo.cz/pull/64 kde potřebuji pomoci s vektorovou grafikou resp. s dodáním erbu Olomouce, prosím.

**Comment by frenzymadness** [comment]
Pyvo je už za 14 dní a dle mého je nejvyší čas začít s propagací.
Já napíšu pár lidem z RH a oslovím i známého podnikatele v Olmíku, zda by nám s propagací nepomohl. Každá pomoc je vítaná, ale hlavní úlohu ponesou místní se svou znalostí okolí @fivaldi a @mcurlej. Prosím aktivitu trackovat zde, abychom nedělali dvakrát totéž.
Aktivitu na twiteru už začal spravovat @honzajavorek, tak snad v tom bude pokračovat.

**Comment by mcurlej** [comment]
@frenzymadness @fivaldi 

V tomto commente som navrhol program:

https://github.com/pyvec/zapojse/issues/61#issuecomment-327161600

Vsimol som si ze na pyvo.cz to nie je. Suhlasime s takym programom zatial?

**Comment by encukou** [comment]
Další program tu má Lumír, a 3 lidi s ním souhlasí – https://github.com/pyvec/zapojse/issues/61#issuecomment-327453076

**Comment by mcurlej** [comment]
@encukou super. nevsimol som si.

**Comment by encukou** [comment]
Pull request s tímto programem: https://github.com/pyvec/pyvo-data/pull/44

@mcurlej a @fivaldi, pozval jsem vás do Githubí organizace a dal jsem vám, jako organizátorům Pyva, přístup k `pyvo-data`. Vítejte :)

**Comment by mcurlej** [comment]
@encukou cool. thx.

**Comment by lzap** [comment]
Já se pokusím přijít. Dneska jsem to zmínil na semináři KMI/SLS který učím na PřF. Příští týden představím program a vysonduju jaký je zájem mezi studenty (celkem 18 zapsaných).
