### ISSUE TITLE
Přeložit talk o mentorování od Anny O.

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#63]
Anna Ossowski měla na PyCon CZ 2017 skvělý talk o mentorství. Poslala mi přepis, a já udělal https://github.com/honzajavorek/become-mentor. Bylo by fajn trochu nakopnout mentorskou kulturu v ČR a myslím, že by pomohlo přeložit tu přednášku. Navíc jsem to Anně slíbil. Co je potřeba udělat?

- Vzít tuhle stránku https://github.com/honzajavorek/become-mentor/blob/master/cs.md a doplnit do ní český překlad :-)
- Počkat, až budou videa z PyCon CZ 2017 a přidat i odkaz na video.

Myslel jsem, že to zvládnu přeložit sám, ale nezvládnu. @zuzejk napadlo, že by se to možná dalo nějak rozdělit mezi PyLadies, že by mohly pomoct. Ono by se to dalo překládat i kousek po kousku, každý jedno okénko... 😄 Zakládám tedy issue, kde bychom se možná mohli nějak zkoordinovat.

**Comment by baradrb** [comment]
Já vám to pak celý proofnu, ale bohužel nestíhám udělat původní překlad.

**Comment by lubojr** [comment]
Pustím se do překladu. :)

**Comment by honzajavorek** [comment]
Překlad přidán! @lubojr 👍 🏅

**Comment by kvbik** [comment]
pecka vsichni! 🎖 dekuji!

bude tenhle text zit takhe na GH? rozhodne by to video mohlo odkazovat na ten prepis totiz!

**Comment by honzajavorek** [comment]
Dobry nápad dát odkaz i z videa. Žít bych to asi nechal na GH. A můžeme to
přesunout klidně na Pyvec. Jestli z toho dělat web - to nevím. Možná spíš
časem rozšířit na python.cz sekci o učení (se) Pythonu, čemuž se stejně
nevyhneme, a tam to nějak zakomponovat.
