### ISSUE TITLE
Formalizovat vztah Pyvce a PSF, PyLadies, DjangoGirls

### ISSUE THREAD

**Issue by encukou** [pyvec/zapojse#66]
Na pyvec.org bychom chtěli říct, že tohle jsou naši partneři:

* [ ] Python Software Foundation
* [ ] PyLadies
* [ ] DjangoGirls

Ale mně se zdá, že o Pyvci tyhle organizace často ani neví, jen podporují stejné projekty jako my. Nazývat je partnery není úplně ono.

**Comment by honzajavorek** [comment]
Co bys navrhoval? Jiné označení, nebo napsat těm organizacím a zeptat se
jich, zda je muzeme nazvat partnery a dat jejich logo na náš web?

**Comment by encukou** [comment]
Jiné označení – třeba říct že s nimi spolupracujeme?
Nebo to druhé – zeptat se, jestli jsme partneři, a jestli ne tak co vlastně :)

**Comment by honzajavorek** [comment]
Za me je dobry napsat "Spolupracujeme s:" v cesky verzi. V anglicky asi "Cooperating with:"? A klidne bych se jich jeste doptal dodatecne, prece jenom jsou tam jejich loga, ale zase pokud napisem ze spolupracujeme, tak to je pravda, ktera by nikomu nemela vadit.

**Comment by honzajavorek** [comment]
Podle mě je tohle vyřešeno v https://github.com/pyvec/pyvec.org/pull/25. Můžeme to tu zavřít? Nevidím důvod proč to nutně formalizovat.
