### ISSUE TITLE
Slack bot oznamujici Pyvo

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#68]
Napadlo me, ze na pyvo.cz by mohlo byt u kazdeho Pyva jasne tlacitko nejen s RSS, ale i neco jako "pridat Slack bot", coz by byl "jednoduchej" bot, ktery by zvladl oznamit do mistnosti ze za tyden nebo primo v ten den bude Pyvo v danem meste. Proc? Protoze Slack pouziva hodne firem a kdyby si tam tohle vyvojari pridali, nezapomenou na Pyvo a jeste navic se o tom dovi i jejich kolegove a muzou se k nim pridat. Ne kazdy je na Twitteru a tak. Navic to oznameni tyden (nebo dva) predem by mohlo byt napsano tak, aby motivovalo k zapsani prednasky.

Mozna zbytecne moc prace, mozna uplna blbost. Nazory?

----

Mozna to neomezovat na Pyvo? Kdyby bylo hotovy https://github.com/pyvec/python.cz/issues/220, dalo by se tam toho oznamovat vic.

**Comment by hroncok** [comment]
Možná jako semestrálka z MI-PYT?

**Comment by aleszoulek** [comment]
Mozna existuje nejakej obecnej slackbot, co integruje kalendare? Tak bychom jen poresili, ze pyvo.cz exportuje iCaly?

(Mohlo by se hodit i na klasicky pridavani to osobniho diare.)

**Comment by honzajavorek** [comment]
Jo, ja si myslim ze mozna uz existuje reseni. Jen ted nemam cas to zkoumat :D

**Comment by encukou** [comment]
@aleszoulek pyvo.cz exportuje iCaly – na hlavní stránce i na stránkách jednotlivých měst máš odkazy na iCal a RSS.

Teď ještě ten Slack.

**Comment by frenzymadness** [comment]
Existuje aplikace pro Slack integrující kalendáře z různých služeb (Google, Office365 ...), ale nic přímo s iCalem.

No a pak je tu jeden skriptík, který by to snad mohl umět: https://github.com/WilliamsNY/slack-ical

**Comment by honzajavorek** [comment]
Viděl bych to tak, že budeme mít tu stránku s Python eventy nebo .ical na Pyva a pak někam akorát dáme návod, jak si to mají lidi zapojit do Slacku, aby je to vůbec napadlo. Programovat nic potřeba asi není.

**Comment by encukou** [comment]
Tohle je už hotové, ne? `#calendar` na Slacku funguje.

**Comment by honzajavorek** [comment]
Ano, a hlavně #announcements :)
