### ISSUE TITLE
Add members to the PyLadiesCZ GtiHub org

### ISSUE THREAD

**Issue by hroncok** [pyvec/zapojse#71]
Could @brabemi and @Zuzanita (Zuzana Pokorná) please be added as members to the [@PyLadiesCZ](https://github.com/PyLadiesCZ) organization on GitHub + have write permissions to [PyLadiesCZ/naucse.python.cz](https://github.com/PyLadiesCZ/naucse.python.cz)? They are both trusted contributors and I can vouch for them. You can find them both listed at https://pyladies.cz/praha/ for a very long time.

**Comment by encukou** [comment]
Added.

**Comment by hroncok** [comment]
TY
